const fs = require("fs");
const listToExclude = [
    "ｐ anｃａｋｅｓwａp",
    "ｐ ａ ｎ cａｋｅｓwａp",
    "ｐ ａnｃａｋｅswa ｐ",
    "ｐ ａncaｋｅｓｗａp",
    "ｐ a ｎ ｃakｅsｗａ ｐ",
    "ｐ a ｎ cａｋeｓwa ｐ",
    "pａ ｎ ｃａkｅsｗａ ｐ",
    "pa ｎ ｃａkeｓｗａ ｐ",
    "pａ ｎ cａｋｅｓｗa ｐ",
    "pａ ｎ caｋｅｓｗa ｐ",
    "pａ ｎ cakｅsｗａ ｐ",
    "pa ｎ ｃａｋeswa ｐ",
    "ｐ a ｎ ｃａｋeswap",
    "pa ｎ ｃａｋｅｓwa ｐ",
    "ｐ anｃａkｅｓｗa ｐ",
    "pa ｎ cakeｓwａp",
    "ｐ anｃａkｅｓｗa ｐ",
    "pａ ｎ ｃakｅswａ ｐ",
    "pａ ｎ cａｋｅswa ｐ",
    "ｐ ａncaｋｅｓｗａp",
    "ｐ ancａkeｓwａp",
    "ｐ ａnｃakeswap",
    "pａ ｎ caｋｅｓｗa ｐ",
    "ｐ ａ ｎ ｃａkｅｓwａp",
    "ｐ ancａkｅswap",
    "pa ｎ cakeｓwａp",
    "ｐ ａ ｎ ｃａkｅｓwa ｐ",
    "pａ ｎ cａｋｅsｗap",
    "ｐ ａnｃakeswap",
    "pa ｎ cａｋesｗａ ｐ",
    "pａ ｎ cａｋeｓwａp",
    "ｐ ａncａｋeswa ｐ",
    "pa ｎ cａｋesｗａ ｐ",
    "ｐ ａ ｎ ｃａkｅｓwａ ｐ",
    "ｐ ａnｃａｋｅｓｗａp",
    "ｐ ａnｃａkｅswap",
    "ｐ ａ ｎ ｃａｋｅsｗa ｐ",
    "ｐ anｃaｋｅswa ｐ",
    "pａ ｎ ｃakeｓｗａ ｐ",
    "pａ ｎ ｃａkｅsｗａ ｐ",
    "ｐ anｃaｋesｗap",
    "ｐ ａnｃａｋｅｓｗａp",
    "pa ｎ caｋeswap",
    "ｐ anｃａｋｅｓwａp",
    "ｐ ａ ｎ cａkｅsｗap",
    "ｐ ａ ｎ ｃaｋｅｓｗa ｐ",
    "ｐ anｃａkeｓwａ ｐ",
    "pａ ｎ cａｋｅswa ｐ",
    "ｐ anｃaｋeｓwap",
    "ｐ ａncakｅｓwａp",
    "ｐ ａncakｅｓwａp",
    "ｐ ａncａｋeswa ｐ",
    "pａ ｎ cａｋｅsｗap",
    "ｐ a ｎ cａkｅsｗa ｐ",
    "pa ｎ ｃａｋｅｓwａp",
    "ｐ a ｎ ｃａｋeswap",
    "ｐ ａ ｎ ｃａkｅｓwa ｐ",
    "pa ｎ cａｋｅｓｗａ ｐ",
    "pa ｎ cａｋｅｓｗａ ｐ",
    "ｐ ａ ｎ ｃａkｅｓwa ｐ",
    "pa ｎ ｃａｋeswa ｐ",
    "ｐ ａncakｅｓwap",
    "pａ ｎ ｃakeｓｗａ ｐ",
    "pａ ｎ cａｋｅswa ｐ",
    "ｐ ａnｃakesｗap",
    "pａ ｎ caｋesｗa ｐ",
    "ｐ a ｎ ｃａｋesｗａ ｐ",
    "pa ｎ cａｋｅｓwap",
    "pa ｎ ｃａｋｅｓwa ｐ",
    "ｐ ａnｃａｋｅswa ｐ",
    "pａ ｎ cａｋeｓwａp",
    "ｐ ａ ｎ ｃaｋｅｓｗa ｐ",
    "pa ｎ cakeｓwａ ｐ",
    "ｐ anｃaｋesｗa ｐ",
    "pａ ｎ ｃａkeｓｗa ｐ",
    "ｐ ａncａkｅswa ｐ",
    "ｐ ancａkeｓwａp",
    "pa ｎ cａkｅｓｗａp",
    "pa ｎ cakeｓwａp",
    "pａ ｎ ｃａｋｅswa ｐ",
    "ｐ ａ ｎ cａｋｅｓwａp",
    "ｐ a ｎ cａｋeｓｗa ｐ",
    "pa ｎ cakeｓwａ ｐ",
    "ｐ ａ ｎ ｃａｋesｗa ｐ",
    "pａ ｎ ｃakｅswａ ｐ",
    "pａ ｎ ｃａkｅsｗａ ｐ",
    "ｐ ａ ｎ ｃakesｗa ｐ",
    "ｐ a ｎ cａｋｅｓｗａ ｐ",
    "ｐ ａnｃａｋesｗａp",
    "ｐ ａncaｋｅｓｗａp",
    "pa ｎ cａkeｓｗａp",
    "pａ ｎ caｋesｗa ｐ",
    "pa ｎ ｃakeswap",
    "ｐ ａnｃakeswap",
    "ｐ ａ ｎ ｃａkｅｓwａ ｐ",
    "pa ｎ ｃａｋeswa ｐ",
    "ｐ ａnｃakesｗap",
    "ｐ ａncａkｅswa ｐ",
    "ｐ anｃａkeｓwａ ｐ",
    "ｐ ａncakｅｓwａp",
    "pa ｎ cａｋｅｓwap",
    "pa ｎ cａkeｓｗａp",
    "ｐ ａncａkｅsｗap",
    "ｐ ancａｋｅｓｗa ｐ",
    "pａ ｎ caｋesｗa ｐ",
    "pａ ｎ cakｅsｗａ ｐ",
    "pａ ｎ ｃａkeｓｗa ｐ",
    "ｐ ａ ｎ cａkｅsｗap",
    "ｐ ａ ｎ cａｋesｗap",
    "ｐ ａ ｎ cａkｅsｗap",
    "ｐ ａ ｎ ｃａkｅｓwａ ｐ",
    "pa ｎ caｋeswap",
    "pａ ｎ caｋｅｓｗa ｐ",
    "pａ ｎ ｃakeｓｗａ ｐ",
    "pa ｎ cａｋｅｓwap",
    "ｐ ａnｃａｋｅｓｗａp",
    "ｐ a ｎ cａｋeｓｗa ｐ",
    "ｐ ａnｃａｋesｗａp",
    "pa ｎ ｃakeswap",
    "ｐ ａ ｎ cａｋｅｓwａp",
    "pa ｎ cakeｓwａ ｐ",
    "ｐ ancａｋｅｓｗa ｐ",
    "ｐ ａnｃａkｅswap",
    "pａ ｎ caｋeswａp",
    "ｐ ａnｃａkｅswap",
    "pa ｎ caｋeswap",
    "pａ ｎ ｃａｋｅswa ｐ",
    "ｐ ａncａkｅswa ｐ",
    "pa ｎ ｃａkeｓｗａ ｐ",
    "ｐ ａ ｎ ｃaｋｅｓｗa ｐ",
    "pa ｎ cａｋesｗａ ｐ",
    "ｐ ａ ｎ cａkesｗａ ｐ",
    "pａ ｎ cａｋｅｓｗa ｐ",
    "pａ ｎ cａｋeｓwａp",
    "pａ ｎ ｃakｅswａ ｐ",
    "ｐ a ｎ ｃａｋeswap",
    "ｐ a ｎ ｃａｋesｗａ ｐ",
    "ｐ a ｎ cａｋeｓwa ｐ",
    "pa ｎ ｃａｋｅｓwａp",
    "ｐ ａ ｎ ｃａｋesｗa ｐ",
    "pa ｎ cａkｅｓｗａp",
    "ｐ a ｎ cａｋeｓwa ｐ",
    "ｐ ａ ｎ ｃａｋｅsｗa ｐ",
    "ｐ a ｎ cａkｅsｗa ｐ",
    "ｐ a ｎ cａkｅsｗa ｐ",
    "ｐ ａ ｎ ｃａkｅｓwａp",
    "ｐ ａ ｎ cａｋesｗap",
    "ｐ anｃａｋｅｓwａp",
    "pa ｎ ｃａkeｓｗａ ｐ",
    "ｐ a ｎ cａｋｅｓｗａ ｐ",
    "ｐ ａ ｎ ｃａkｅｓwａp",
    "ｐ ａ ｎ ｃakesｗa ｐ",
    "pa ｎ cａｋｅｓｗａ ｐ",
    "ｐ ａnｃakesｗap",
    "ｐ ａncａkｅsｗap",
    "ｐ ａ ｎ caｋｅｓwap",
    "ｐ anｃaｋｅswa ｐ",
    "pａ ｎ caｋeswａp",
    "ｐ ａnｃａｋｅswa ｐ",
    "ｐ anｃaｋeｓwap",
    "ｐ anｃaｋｅswa ｐ",
    "pａ ｎ cａｋｅsｗap",
    "ｐ anｃａkeｓwａ ｐ",
    "ｐ ａ ｎ ｃakesｗa ｐ",
    "ｐ a ｎ ｃａｋesｗａ ｐ",
    "ｐ ａ ｎ cａkesｗａ ｐ",
    "ｐ a ｎ cａｋeｓｗa ｐ",
    "pa ｎ ｃaｋｅｓwa ｐ",
    "ｐ ancａkeｓwａp",
    "ｐ anｃaｋeｓwap",
    "ｐ a ｎ ｃakｅsｗａ ｐ",
    "ｐ ａncakｅｓwap",
    "pａ ｎ ｃａｋｅswa ｐ",
    "pａ ｎ caｋeswａp",
    "ｐ anｃａkｅｓｗa ｐ",
    "ｐ ancａｋｅｓｗa ｐ",
    "ｐ ancａkｅswap",
    "ｐ ａ ｎ ｃａｋesｗa ｐ",
    "pａ ｎ cakｅsｗａ ｐ",
    "pa ｎ ｃaｋｅｓwa ｐ",
    "pa ｎ cａkｅｓｗａp",
    "ｐ anｃaｋesｗa ｐ",
    "ｐ ａncakｅｓwap",
    "ｐ ancａkｅswap",
    "ｐ ａnｃａｋesｗａp",
    "pａ ｎ ｃａkeｓｗa ｐ",
    "ｐ anｃaｋesｗap",
    "pa ｎ ｃakeswap",
    "pa ｎ ｃａｋｅｓwａp",
    "ｐ a ｎ ｃakｅsｗａ ｐ",
    "ｐ ａ ｎ ｃａｋｅsｗa ｐ",
    "pa ｎ ｃａｋｅｓwa ｐ",
    "pa ｎ cａkeｓｗａp",
    "ｐ ａncａkｅsｗap",
    "ｐ anｃaｋesｗap",
    "ｐ a ｎ cａｋｅｓｗａ ｐ",
    "ｐ ａncａｋeswa ｐ",
    "ｐ anｃaｋesｗa ｐ",
    "ｐ ａ ｎ cａkesｗａ ｐ",
    "pａ ｎ cａｋｅｓｗa ｐ",
    "pa ｎ ｃaｋｅｓwa ｐ",
    "ｐ ａ ｎ cａｋesｗap",
    "pａ ｎ ｃａkｅｓｗａp",
    "ｐ a ｎ ｃaｋｅｓｗa ｐ",
    "pa ｎ ｃａｋｅｓwa ｐ",
    "pa ｎ cａｋｅｓwａ ｐ",
    "pa ｎ ｃaｋeｓwａp",
    "pa ｎ ｃaｋeｓwａp",
    "ｐ ancａkｅsｗap",
    "ｐ ancａkｅsｗap",
    "pａ ｎ ｃａkｅｓｗａp",
    "pａ ｎ ｃａkｅｓｗａp",
    "pa ｎ ｃaｋｅsｗａp",
    "pa ｎ ｃaｋｅsｗａp",
    "pa ｎ cａｋｅｓwａ ｐ",
    "pa ｎ ｃａｋｅｓwa ｐ",
    "pa ｎ ｃａｋｅｓwa ｐ",
    "ｐ a ｎ ｃaｋｅｓｗa ｐ",
    "pａ ｎ ｃakｅsｗａ ｐ",
    "ｐ ancａkｅsｗap",
    "pa ｎ ｃaｋeｓwａp",
    "pa ｎ ｃaｋｅsｗａp",
    "pａ ｎ ｃakｅsｗａ ｐ",
    "ｐ a ｎ ｃaｋｅｓｗa ｐ",
    "pａ ｎ ｃakｅsｗａ ｐ",
    "pa ｎ cａｋｅｓwａ ｐ",
    "pa ｎ ｃaｋｅswap",
    "ｐ ancａｋeswa ｐ",
    "ｐ ancａｋeswa ｐ",
    "pａ ｎ cakesｗａ ｐ",
    "pａ ｎ ｃakｅswa ｐ",
    "pa ｎ ｃaｋｅswap",
    "ｐ a ｎ caｋeswａp",
    "pａ ｎ cakesｗａ ｐ",
    "ｐ ancａｋeswa ｐ",
    "ｐ a ｎ caｋeswａp",
    "pａ ｎ ｃakｅswa ｐ",
    "pａ ｎ cakesｗａ ｐ",
    "ｐ ａ ｎ cakｅsｗａ ｐ",
    "pａ ｎ ｃakｅswa ｐ",
    "ｐ ａ ｎ cakｅsｗａ ｐ",
    "ｐ ａ ｎ cakｅsｗａ ｐ",
    "ｐ a ｎ caｋeswａp",
    "pa ｎ ｃaｋｅswap",
    "pa ｎ ｃaｋｅswａp",
    "pa ｎ caｋesｗa ｐ",
    "ｐ a ｎ caｋｅswa ｐ",
    "ｐ ａnｃａkｅｓwa ｐ",
    "pa ｎ caｋesｗa ｐ",
    "pa ｎ ｃaｋｅswａp",
    "pa ｎ ｃakｅｓｗa ｐ",
    "pa ｎ ｃakｅｓｗa ｐ",
    "pa ｎ cakｅｓwａp",
    "ｐ a ｎ caｋｅswa ｐ",
    "ｐ ａnｃａkｅｓwa ｐ",
    "pa ｎ cakｅｓwａp",
    "ｐ ａnｃａkｅｓwa ｐ",
    "ｐ a ｎ ｃａｋｅswap",
    "pa ｎ ｃaｋｅswａp",
    "pａ ｎ cakeswａp",
    "ｐ a ｎ ｃａｋｅswap",
    "pa ｎ caｋesｗa ｐ",
    "pa ｎ ｃakｅｓｗa ｐ",
    "ｐ a ｎ ｃａｋｅswap",
    "ｐ a ｎ caｋｅswa ｐ",
    "pa ｎ cakｅｓwａp",
    "pａ ｎ cａkｅｓｗap",
    "pａ ｎ cａkｅｓｗap",
    "pａ ｎ cａkｅｓｗap",
    "pａ ｎ cakeswａp",
    "pａ ｎ cakeswａp",
    "ｐ a ｎ ｃａkｅsｗap",
    "ｐ ａnｃａｋｅｓwap",
    "ｐ ａnｃａｋｅｓwap",
    "ｐ a ｎ ｃａkeswap",
    "ｐ anｃaｋeｓｗａ ｐ",
    "ｐ anｃakeｓwa ｐ",
    "ｐ a ｎ cａkeｓwａp",
    "ｐ a ｎ ｃａkeswap",
    "pａ ｎ ｃakｅｓｗa ｐ",
    "ｐ a ｎ ｃａｋeｓwa ｐ",
    "pａ ｎ ｃakｅｓｗa ｐ",
    "ｐ a ｎ ｃａkeswap",
    "ｐ a ｎ cａkeｓwａp",
    "ｐ ancakeｓｗa ｐ",
    "ｐ anｃakeｓwa ｐ",
    "ｐ anｃakeｓwa ｐ",
    "ｐ a ｎ ｃａｋeｓwa ｐ",
    "ｐ anｃaｋeｓｗａ ｐ",
    "ｐ ancakeｓｗa ｐ",
    "ｐ ａnｃａｋｅｓwap",
    "ｐ a ｎ ｃａｋeｓwa ｐ",
    "ｐ a ｎ ｃａkｅsｗap",
    "ｐ a ｎ ｃａkｅsｗap",
    "ｐ a ｎ cａkeｓwａp",
    "ｐ ancakeｓｗa ｐ",
    "pａ ｎ ｃakｅｓｗa ｐ",
    "ｐ anｃaｋeｓｗａ ｐ",
    "pａ ｎ ｃａkｅｓｗａ ｐ",
    "pa ｎ ｃａｋｅsｗap",
    "pa ｎ cａｋesｗａ ｐ",
    "ｐ ａncａｋｅｓｗa ｐ",
    "pa ｎ cａｋesｗａ ｐ",
    "ｐ anｃａｋｅsｗap",
    "pa ｎ ｃａｋｅsｗap",
    "ｐ ａncａｋｅｓｗa ｐ",
    "ｐ ａ ｎ ｃａｋｅswap",
    "pa ｎ cａｋesｗａ ｐ",
    "ｐ ａncaｋesｗａp",
    "ｐ ａnｃａｋｅｓwａ ｐ",
    "pａ ｎ ｃａkｅｓｗａ ｐ",
    "ｐ ａnｃａｋｅｓwａ ｐ",
    "ｐ ａncａｋｅｓｗa ｐ",
    "ｐ ａ ｎ ｃａｋｅswap",
    "ｐ ａ ｎ ｃａｋｅswap",
    "pa ｎ ｃａｋｅsｗap",
    "ｐ anｃａｋｅsｗap",
    "ｐ anｃａｋｅsｗap",
    "ｐ ａncaｋesｗａp",
    "pａ ｎ ｃａkｅｓｗａ ｐ",
    "ｐ ａncaｋesｗａp",
    "ｐ ａnｃａｋｅｓwａ ｐ",
    "ｐ ａ ｎ ｃａｋeｓwａp",
    "ｐ a ｎ ｃakｅswａ ｐ",
    "ｐ a ｎ ｃakｅswa ｐ",
    "ｐ ａ ｎ ｃaｋｅsｗap",
    "ｐ a ｎ ｃａｋeｓwａp",
    "ｐ a ｎ ｃakｅswａ ｐ",
    "ｐ ａnｃakｅsｗap",
    "pa ｎ ｃａｋｅsｗa ｐ",
    "ｐ ａ ｎ ｃakeｓｗa ｐ",
    "ｐ ａnｃakｅsｗap",
    "ｐ a ｎ ｃakｅswａ ｐ",
    "ｐ ａ ｎ ｃaｋｅsｗap",
    "ｐ ａnｃakｅsｗap",
    "ｐ ａ ｎ ｃaｋｅsｗap",
    "pa ｎ ｃａｋｅsｗa ｐ",
    "ｐ ancakｅswa ｐ",
    "ｐ a ｎ ｃａｋeｓwａp",
    "ｐ ａ ｎ ｃａｋeｓwａp",
    "ｐ ａ ｎ ｃakeｓｗa ｐ",
    "pa ｎ ｃａｋｅsｗa ｐ",
    "ｐ a ｎ ｃａｋeｓwａp",
    "ｐ a ｎ ｃakｅswa ｐ",
    "ｐ a ｎ ｃakｅswa ｐ",
    "ｐ ancakｅswa ｐ",
    "ｐ ａ ｎ ｃakeｓｗa ｐ",
    "ｐ ancakｅswa ｐ",
    "ｐ ａ ｎ ｃａｋeｓwａp",
    "pa ｎ caｋeｓwａ ｐ",
    "pa ｎ ｃａkｅswap",
    "pa ｎ cａｋｅｓwａp",
    "ｐ ａ ｎ ｃaｋeswａ ｐ",
    "ｐ a ｎ cａkeｓwa ｐ",
    "ｐ ancａｋｅｓｗａp",
    "ｐ ａncａｋesｗap",
    "ｐ ａ ｎ cakeｓwa ｐ",
    "ｐ ancａｋeswap",
    "ｐ a ｎ ｃａｋｅsｗａ ｐ",
    "pa ｎ ｃaｋｅswａ ｐ",
    "ｐ a ｎ ｃaｋｅｓwa ｐ",
    "ｐ anｃａkｅｓwap",
    "pａ ｎ cａkesｗａ ｐ",
    "ｐ ａnｃakeswａp",
    "pａ ｎ cakeｓwa ｐ",
    "ｐ ａ ｎ cakｅｓwａ ｐ",
    "ｐ anｃakｅｓｗap",
    "pa ｎ caｋｅswａp",
    "ｐ a ｎ cakｅsｗａp",
    "ｐ ａnｃａkeswａ ｐ",
    "ｐ ａ ｎ ｃａｋｅswａp",
    "ｐ ａ ｎ ｃaｋesｗa ｐ",
    "ｐ anｃakｅsｗap",
    "pａ ｎ ｃaｋｅｓｗａp",
    "ｐ a ｎ ｃａｋｅswａ ｐ",
    "pａ ｎ ｃakeｓwa ｐ",
    "pａ ｎ cａｋｅswａp",
    "ｐ ａ ｎ ｃaｋｅｓwａ ｐ",
    "ｐ ａ ｎ ｃakｅｓｗa ｐ",
    "pａ ｎ ｃaｋeswａp",
    "ｐ ａnｃａkeｓｗap",
    "pa ｎ caｋeswa ｐ",
    "ｐ a ｎ ｃaｋeswap",
    "pa ｎ ｃakeｓｗap",
    "pa ｎ ｃａkeswａp",
    "ｐ ａ ｎ caｋeｓｗap",
    "pａ ｎ ｃａｋeｓwa ｐ",
    "ｐ a ｎ ｃakeｓwap",
    "ｐ a ｎ cａkeswａ ｐ",
    "pａ ｎ ｃakeｓwａp",
    "ｐ a ｎ ｃａｋｅｓwap",
    "ｐ a ｎ ｃａkｅsｗa ｐ",
    "pa ｎ ｃａｋeｓwａp",
    "ｐ ａ ｎ ｃａｋesｗap",
    "pａ ｎ caｋeｓwa ｐ",
    "pa ｎ cａkeｓｗap",
    "ｐ a ｎ cａkｅswａp",
    "pａ ｎ caｋｅｓｗａ ｐ",
    "ｐ ａnｃakeｓｗａp",
    "ｐ ａ ｎ ｃａｋeｓｗａ ｐ",
    "pａ ｎ cａｋeswap",
    "ｐ ａncaｋｅswa ｐ",
    "pa ｎ cａｋeswap",
    "pａ ｎ ｃａｋeｓｗap",
    "ｐ ａ ｎ cakesｗａ ｐ",
    "ｐ ａ ｎ ｃakｅsｗａp",
    "ｐ ａncａkeswap",
    "ｐ a ｎ cakeswa ｐ",
    "ｐ ａ ｎ cakｅswａ ｐ",
    "pa ｎ ｃａｋｅswａp",
    "ｐ anｃａｋｅswap",
    "ｐ ａncａkeｓｗa ｐ",
    "pa ｎ ｃaｋｅｓｗap",
    "pa ｎ cａkｅswａ ｐ",
    "ｐ ａ ｎ caｋｅsｗａp",
    "pa ｎ cａkｅｓｗa ｐ",
    "pａ ｎ cakｅswap",
    "ｐ a ｎ cａkｅswａ ｐ",
    "pa ｎ cａkesｗａ ｐ",
    "pa ｎ ｃａkｅswa ｐ",
    "pa ｎ caｋeｓwａp",
    "ｐ ａ ｎ cａｋｅｓwap",
    "ｐ ａ ｎ ｃａkesｗa ｐ",
    "pa ｎ cakeｓｗａ ｐ",
    "ｐ ancakｅsｗａ ｐ",
    "ｐ ancａkｅｓwａ ｐ",
    "pa ｎ caｋｅｓwap",
    "ｐ a ｎ ｃakeswａp",
    "ｐ ａ ｎ ｃａkeswap",
    "pａ ｎ ｃａｋesｗａp",
    "ｐ a ｎ ｃakｅswａp",
    "ｐ ａ ｎ ｃaｋｅｓwａp",
    "pａ ｎ ｃakｅswａp",
    "ｐ ancａｋeｓｗa ｐ",
    "ｐ ａ ｎ cakesｗａp",
    "ｐ a ｎ cakｅｓwａp",
    "pａ ｎ ｃaｋｅｓwap",
    "pａ ｎ ｃａｋeｓwａ ｐ",
    "pa ｎ ｃaｋeswa ｐ",
    "pａ ｎ cａkeｓｗａp",
    "ｐ anｃａｋeｓｗa ｐ",
    "ｐ ａncaｋｅｓwａp",
    "pａ ｎ ｃaｋeswap",
    "pａ ｎ ｃａｋeswa ｐ",
    "pa ｎ ｃakｅｓwap",
    "ｐ a ｎ ｃａkｅswa ｐ",
    "pa ｎ ｃaｋeｓｗａp",
    "ｐ ａ ｎ ｃaｋｅsｗa ｐ",
    "ｐ a ｎ ｃａｋｅｓｗａ ｐ",
    "pａ ｎ cakｅswａ ｐ",
    "pａ ｎ ｃａｋesｗａ ｐ",
    "pａ ｎ ｃaｋeｓwap",
    "ｐ a ｎ caｋｅｓｗap",
    "ｐ anｃakeｓwａ ｐ",
    "pａ ｎ ｃakesｗa ｐ",
    "ｐ ａncａkesｗa ｐ",
    "ｐ anｃａｋesｗａ ｐ",
    "pa ｎ caｋｅｓｗａ ｐ",
    "ｐ ancakeswa ｐ",
    "ｐ ａncakｅswａp",
    "ｐ ａ ｎ cａｋｅｓwａ ｐ",
    "ｐ a ｎ ｃaｋｅswap",
    "ｐ ａ ｎ ｃakｅｓｗａ ｐ",
    "pa ｎ caｋｅｓｗa ｐ",
    "pa ｎ cａkｅswap",
    "pａ ｎ cａkeｓｗａ ｐ",
    "ｐ ancａkｅswａp",
    "ｐ a ｎ caｋｅｓwａ ｐ",
    "ｐ ａ ｎ cａkｅｓｗa ｐ",
    "pa ｎ ｃaｋｅｓｗa ｐ",
    "ｐ ancaｋesｗａ ｐ",
    "pａ ｎ cakｅswa ｐ",
    "ｐ ａ ｎ caｋｅsｗa ｐ",
    "ｐ ａnｃａkｅｓｗａ ｐ",
    "ｐ ａ ｎ caｋｅswa ｐ",
    "ｐ ａ ｎ ｃakｅｓwa ｐ",
    "pa ｎ cａｋeｓｗａp",
    "pa ｎ ｃaｋeswａ ｐ",
    "pa ｎ ｃａｋeｓｗａ ｐ",
    "pａ ｎ cａkｅｓｗａp",
    "pa ｎ ｃａｋｅsｗａ ｐ",
    "ｐ a ｎ caｋeｓｗａ ｐ",
    "pa ｎ cakeｓwap",
    "ｐ ａ ｎ cakｅｓｗap",
    "ｐ a ｎ ｃaｋｅsｗap",
    "ｐ anｃａkesｗａ ｐ",
    "pａ ｎ cａkeswa ｐ",
    "ｐ ancaｋｅｓｗap",
    "pａ ｎ cａｋeswａp",
    "pａ ｎ cａｋesｗap",
    "pa ｎ ｃａkeｓｗap",
    "pa ｎ cakeｓwa ｐ",
    "ｐ anｃaｋｅｓｗap",
    "ｐ anｃａkｅｓｗａp",
    "ｐ ａncａｋｅｓwａ ｐ",
    "ｐ ａncaｋeswap",
    "pa ｎ cａｋｅｓｗａp",
    "ｐ anｃaｋｅsｗａ ｐ",
    "ｐ a ｎ ｃakｅsｗap",
    "ｐ ａ ｎ ｃａｋｅｓwa ｐ",
    "pa ｎ ｃaｋｅsｗap",
    "pa ｎ ｃakeｓwa ｐ",
    "ｐ a ｎ ｃａｋeswａp",
    "ｐ a ｎ cａｋesｗａp",
    "pa ｎ ｃａｋｅsｗａp",
    "pa ｎ cａkｅｓｗap",
    "ｐ a ｎ cａｋｅsｗap",
    "pa ｎ ｃａkesｗa ｐ",
    "ｐ ａ ｎ cakｅｓwap",
    "ｐ a ｎ ｃａｋeswａ ｐ",
    "pa ｎ cakｅｓwａ ｐ",
    "pa ｎ cａｋeｓｗa ｐ",
    "ｐ a ｎ ｃａkesｗa ｐ",
    "ｐ ａncakeswａp",
    "ｐ ａ ｎ cａkeｓwａp",
    "pａ ｎ ｃaｋｅswap",
    "ｐ a ｎ ｃaｋeswａ ｐ",
    "pａ ｎ caｋｅｓｗap",
    "pａ ｎ ｃaｋｅsｗａp",
    "ｐ a ｎ cａkeｓwａ ｐ",
    "pa ｎ ｃａkｅsｗa ｐ",
    "ｐ ancakｅsｗa ｐ",
    "ｐ a ｎ cａｋｅｓwa ｐ",
    "ｐ ancａｋｅｓｗａ ｐ",
    "pａ ｎ ｃａｋｅswａp",
    "ｐ ａ ｎ ｃａｋeｓwa ｐ",
    "pa ｎ ｃａkeswa ｐ",
    "ｐ a ｎ ｃａkｅｓwa ｐ",
    "ｐ ancaｋeｓｗa ｐ",
    "ｐ ancakｅsｗap",
    "ｐ ａnｃaｋesｗａp",
    "ｐ ａnｃakｅsｗａp",
    "ｐ a ｎ cakesｗａp",
    "ｐ ａnｃakｅsｗa ｐ",
    "pa ｎ caｋeｓwap",
    "ｐ a ｎ cakeswap",
    "ｐ ａ ｎ ｃakeｓｗａ ｐ",
    "ｐ a ｎ cakeｓwａ ｐ",
    "pａ ｎ ｃaｋeｓｗa ｐ",
    "pa ｎ ｃａｋeｓｗap",
    "ｐ ａ ｎ ｃakesｗａp",
    "ｐ ａnｃａｋeｓｗａp",
    "ｐ ａ ｎ ｃａｋｅｓwap",
    "pa ｎ cａｋｅswａ ｐ",
    "ｐ ａ ｎ ｃａｋｅsｗａp",
    "ｐ a ｎ ｃａkeｓwａ ｐ",
    "ｐ ａnｃakｅswa ｐ",
    "pa ｎ ｃakｅｓwa ｐ",
    "ｐ a ｎ ｃａｋｅｓwａp",
    "ｐ ａnｃａｋeｓwａp",
    "ｐ ａ ｎ ｃakeswap",
    "ｐ a ｎ cakｅswa ｐ",
    "ｐ a ｎ ｃakeｓwａ ｐ",
    "ｐ anｃａkｅswap",
    "pａ ｎ ｃａｋｅsｗａ ｐ",
    "ｐ ancaｋesｗａp",
    "ｐ ａncaｋｅswａp",
    "ｐ ａncａkeｓｗａp",
    "pａ ｎ ｃａｋｅｓwａp",
    "ｐ anｃａkesｗａp",
    "ｐ ａncａkｅｓwａp",
    "pa ｎ ｃａｋeｓｗa ｐ",
    "ｐ ａnｃａkeｓｗａp",
    "pa ｎ cakｅｓｗap",
    "ｐ ａ ｎ ｃakeｓwa ｐ",
    "ｐ ａnｃａkesｗａp",
    "ｐ a ｎ cakｅｓｗa ｐ",
    "ｐ a ｎ caｋｅｓwa ｐ",
    "ｐ ａncａｋesｗａ ｐ",
    "ｐ ancａｋeｓwa ｐ",
    "ｐ ａ ｎ cａkeｓwa ｐ",
    "ｐ ａ ｎ ｃakeｓwａ ｐ",
    "pa ｎ cａkｅsｗa ｐ",
    "pa ｎ cakｅsｗap",
    "ｐ ａ ｎ cａkeｓwａ ｐ",
    "ｐ a ｎ caｋesｗａp",
    "pａ ｎ ｃaｋesｗap",
    "pａ ｎ cakｅsｗa ｐ",
    "ｐ ａnｃakｅｓｗa ｐ",
    "ｐ a ｎ cａｋeswａp",
    "ｐ a ｎ cａkeｓwap",
    "ｐ anｃａｋeswa ｐ",
    "ｐ a ｎ ｃａｋeｓwａ ｐ",
    "ｐ ａ ｎ cａｋｅｓｗａ ｐ",
    "ｐ a ｎ ｃａｋesｗap",
    "ｐ a ｎ ｃａkeｓｗａp",
    "pa ｎ ｃａｋeswａp",
    "ｐ ancakesｗap",
    "ｐ ａ ｎ caｋｅswａp",
    "ｐ ａ ｎ caｋeｓｗa ｐ",
    "ｐ a ｎ ｃａkｅｓwａp",
    "pa ｎ cakｅswa ｐ",
    "pa ｎ ｃａkｅｓｗａp",
    "ｐ ancａkeｓｗap",
    "ｐ ａncakｅsｗａ ｐ",
    "ｐ ａncakeｓwap",
    "pａ ｎ ｃａｋeｓｗａp",
    "pa ｎ cａｋｅsｗａp",
    "pａ ｎ cａｋesｗａ ｐ",
    "ｐ ancakｅｓwa ｐ",
    "pa ｎ caｋｅｓｗap",
    "ｐ ａ ｎ caｋｅｓwa ｐ",
    "pａ ｎ ｃａkｅswａp",
    "pａ ｎ caｋeｓwａp",
    "pa ｎ ｃａｋeswａ ｐ",
    "pａ ｎ cａkｅsｗap",
    "pa ｎ ｃaｋeｓｗap",
    "ｐ ａnｃａkesｗa ｐ",
    "ｐ ａ ｎ ｃａkｅｓｗa ｐ",
    "ｐ ａ ｎ ｃaｋｅswａ ｐ",
    "ｐ a ｎ ｃaｋesｗａp",
    "ｐ a ｎ ｃａｋｅｓwa ｐ",
    "ｐ a ｎ ｃakｅｓwａ ｐ",
    "pa ｎ caｋｅswa ｐ",
    "ｐ ａ ｎ caｋｅswap",
    "ｐ ａ ｎ cａｋｅｓｗa ｐ",
    "ｐ ａ ｎ cａkｅswａ ｐ",
    "pａ ｎ caｋeｓwａ ｐ",
    "pａ ｎ cａｋｅｓｗａ ｐ",
    "pa ｎ cａｋeｓwa ｐ",
    "ｐ anｃaｋeswap",
    "ｐ ancaｋeｓｗａp",
    "pa ｎ ｃaｋｅｓwａp",
    "ｐ a ｎ cakeｓｗap",
    "ｐ ａnｃaｋｅswａp",
    "ｐ ancａkｅｓｗａ ｐ",
    "pａ ｎ cakesｗa ｐ",
    "ｐ a ｎ caｋｅswａ ｐ",
    "ｐ ａncakｅsｗap",
    "ｐ ａncakｅｓｗa ｐ",
    "ｐ a ｎ cakｅsｗａ ｐ",
    "ｐ ａ ｎ ｃaｋeswａp",
    "pａ ｎ cａkeswａ ｐ",
    "ｐ ａ ｎ caｋｅｓwａ ｐ",
    "pa ｎ cａｋeswａp",
    "pａ ｎ cａｋeｓｗap",
    "pａ ｎ cａｋｅｓwａp",
    "ｐ ａnｃaｋｅｓｗａ ｐ",
    "pa ｎ ｃaｋesｗap",
    "pa ｎ ｃａkeｓwａp",
    "ｐ ａ ｎ ｃａkｅsｗａ ｐ",
    "ｐ ancakeｓwa ｐ",
    "pa ｎ cａkｅｓｗａ ｐ",
    "ｐ ａncａｋｅswap",
    "ｐ ａ ｎ ｃａkeswa ｐ",
    "ｐ anｃａkｅsｗａp",
    "ｐ ａnｃakeｓwａp",
    "ｐ a ｎ cａｋeswａ ｐ",
    "pａ ｎ caｋｅswａp",
    "ｐ ancａkeswａp",
    "pa ｎ cakesｗa ｐ",
    "ｐ ａ ｎ ｃakeswa ｐ",
    "ｐ ａ ｎ ｃａkesｗａp",
    "ｐ ａ ｎ ｃａkｅsｗap",
    "ｐ ancａkesｗａp",
    "ｐ a ｎ ｃａｋｅｓwａ ｐ",
    "ｐ a ｎ ｃakｅｓｗａp",
    "ｐ ancakeｓｗap",
    "ｐ ａncａｋｅsｗa ｐ",
    "ｐ ａ ｎ cakeｓｗａp",
    "ｐ ancakeｓwap",
    "ｐ ancａkesｗa ｐ",
    "ｐ ancａｋesｗap",
    "ｐ ａ ｎ cａｋeｓwａp",
    "pａ ｎ cａｋesｗa ｐ",
    "pa ｎ caｋeｓｗa ｐ",
    "ｐ a ｎ ｃaｋesｗa ｐ",
    "ｐ anｃａkeswａp",
    "ｐ ａnｃakｅｓwa ｐ",
    "ｐ ａ ｎ ｃakeｓｗap",
    "pa ｎ cａkeswap",
    "ｐ a ｎ ｃａｋｅsｗa ｐ",
    "ｐ a ｎ cakｅsｗap",
    "ｐ anｃaｋｅswａ ｐ",
    "ｐ anｃａkeswap",
    "pa ｎ ｃａｋesｗa ｐ",
    "ｐ a ｎ ｃａｋesｗa ｐ",
    "pａ ｎ cakeswa ｐ",
    "pａ ｎ ｃａｋｅswap",
    "ｐ ancaｋeswap",
    "ｐ a ｎ caｋｅｓｗa ｐ",
    "ｐ ａ ｎ caｋesｗa ｐ",
    "ｐ ancaｋｅsｗap",
    "ｐ ａ ｎ ｃakｅｓwap",
    "pａ ｎ ｃａｋesｗa ｐ",
    "pａ ｎ cａkｅsｗａp",
    "ｐ anｃaｋeｓｗa ｐ",
    "ｐ ａncakｅｓwa ｐ",
    "ｐ ancａkｅｓｗap",
    "ｐ anｃａkｅｓｗap",
    "ｐ a ｎ ｃaｋｅｓwap",
    "ｐ ancaｋeｓwａ ｐ",
    "pａ ｎ ｃａｋｅｓｗａp",
    "ｐ ａnｃａｋesｗａ ｐ",
    "pa ｎ ｃａkｅｓwap",
    "ｐ ancａｋｅsｗa ｐ",
    "ｐ ａ ｎ ｃakesｗａ ｐ",
    "ｐ anｃａｋｅswａp",
    "pａ ｎ ｃaｋｅｓwａ ｐ",
    "ｐ ａnｃａｋｅswap",
    "ｐ ａncａｋesｗa ｐ",
    "ｐ ancａkｅｓｗａp",
    "ｐ ａ ｎ caｋeｓｗａ ｐ",
    "pａ ｎ ｃakesｗap",
    "ｐ ａnｃaｋｅswａ ｐ",
    "pa ｎ cａｋｅｓｗa ｐ",
    "ｐ ancaｋeｓｗap",
    "ｐ ａnｃａｋeswａ ｐ",
    "pａ ｎ caｋｅｓwａp",
    "ｐ ａ ｎ ｃａkeｓｗａ ｐ",
    "ｐ anｃakeｓwａp",
    "ｐ ancakｅｓｗａp",
    "ｐ a ｎ ｃaｋeｓｗａ ｐ",
    "pa ｎ cａkesｗａp",
    "pa ｎ cａｋeｓwap",
    "ｐ ａnｃaｋｅswa ｐ",
    "ｐ a ｎ ｃａkｅｓｗａ ｐ",
    "ｐ ａnｃakesｗa ｐ",
    "ｐ a ｎ ｃakｅｓwa ｐ",
    "pa ｎ ｃａkesｗａp",
    "pa ｎ cａkｅswａp",
    "ｐ ａncａkesｗａ ｐ",
    "pａ ｎ ｃａkeｓｗａp",
    "ｐ ａncａｋｅsｗap",
    "ｐ ａ ｎ cａkｅｓｗap",
    "ｐ ancａｋeｓｗａ ｐ",
    "ｐ ａncａkｅｓｗap",
    "ｐ a ｎ ｃａｋesｗａp",
    "pａ ｎ caｋeｓｗap",
    "pａ ｎ ｃakｅｓwａ ｐ",
    "ｐ a ｎ ｃakeｓｗa ｐ",
    "pａ ｎ ｃaｋｅｓwａp",
    "pａ ｎ cａkeｓｗa ｐ",
    "ｐ ａncａｋeｓwa ｐ",
    "ｐ ａncａkｅｓwａ ｐ",
    "ｐ ａnｃaｋeｓwａp",
    "ｐ a ｎ cakesｗa ｐ",
    "ｐ ａ ｎ caｋｅsｗａ ｐ",
    "pａ ｎ cａkｅｓwａ ｐ",
    "ｐ ａncakeｓｗａp",
    "pa ｎ ｃａkeswap",
    "ｐ a ｎ ｃaｋeｓｗa ｐ",
    "pa ｎ ｃａkｅｓwa ｐ",
    "ｐ ancakｅsｗａp",
    "ｐ anｃａkeｓｗａ ｐ",
    "ｐ a ｎ ｃakeｓwａp",
    "pa ｎ cakesｗａ ｐ",
    "ｐ ancａkｅsｗａp",
    "pａ ｎ caｋｅswa ｐ",
    "ｐ ancａｋｅｓwap",
    "ｐ anｃakeｓｗa ｐ",
    "ｐ ａ ｎ ｃaｋeｓｗa ｐ",
    "ｐ anｃakeswa ｐ",
    "pa ｎ cａkeｓｗa ｐ",
    "ｐ a ｎ ｃaｋｅswａp",
    "ｐ a ｎ cａkｅｓwap",
    "pａ ｎ ｃａkesｗａ ｐ",
    "pa ｎ cakｅswａ ｐ",
    "ｐ ancakｅｓｗap",
    "ｐ ａ ｎ ｃａｋｅswａ ｐ",
    "ｐ ａncａｋｅｓwａp",
    "ｐ a ｎ ｃａkｅｓｗa ｐ",
    "pa ｎ ｃaｋeｓｗａ ｐ",
    "ｐ ａncａkesｗａp",
    "ｐ ａnｃaｋｅsｗａp",
    "pa ｎ ｃａkeｓｗａp",
    "pａ ｎ ｃａkesｗa ｐ",
    "ｐ a ｎ ｃakesｗap",
    "pａ ｎ ｃａkeｓwa ｐ",
    "ｐ ａ ｎ ｃaｋeｓwａ ｐ",
    "ｐ ａ ｎ cakeｓwａp",
    "pａ ｎ ｃａkeswap",
    "ｐ ａnｃａkｅswa ｐ",
    "ｐ a ｎ ｃaｋｅsｗa ｐ",
    "ｐ ａ ｎ ｃａkeswａp",
    "pa ｎ cａkｅｓwap",
    "pａ ｎ cａkｅｓｗa ｐ",
    "pａ ｎ ｃａkｅswap",
    "ｐ ancaｋeｓｗａ ｐ",
    "ｐ ａ ｎ ｃaｋesｗａ ｐ",
    "ｐ ａnｃaｋｅｓwa ｐ",
    "pａ ｎ ｃakeswap",
    "ｐ a ｎ cａkeswa ｐ",
    "pａ ｎ cａｋｅsｗａ ｐ",
    "ｐ a ｎ cａkeswａp",
    "ｐ a ｎ ｃaｋeｓｗａp",
    "ｐ anｃａｋeｓwａ ｐ",
    "ｐ a ｎ cａｋeｓｗap",
    "pａ ｎ ｃａkeｓwａp",
    "pa ｎ cａkeswａp",
    "ｐ anｃａｋeｓwap",
    "ｐ a ｎ caｋeｓｗap",
    "ｐ a ｎ cakeｓｗａ ｐ",
    "ｐ a ｎ ｃａkｅswap",
    "ｐ ａnｃａｋeｓwａ ｐ",
    "ｐ a ｎ cａｋeｓwａp",
    "ｐ anｃaｋeｓwa ｐ",
    "ｐ ａnｃａｋｅsｗａ ｐ",
    "ｐ a ｎ ｃakｅｓwａp",
    "pa ｎ ｃａｋｅｓｗa ｐ",
    "pａ ｎ caｋｅｓwa ｐ",
    "pａ ｎ ｃａｋeswａp",
    "pａ ｎ cａｋeｓｗａ ｐ",
    "ｐ a ｎ ｃakｅｓｗa ｐ",
    "pａ ｎ cａｋｅsｗａp",
    "ｐ ａncａｋeｓｗａp",
    "ｐ ａnｃａｋeｓｗap",
    "ｐ a ｎ cａkeｓｗap",
    "ｐ ａ ｎ ｃaｋｅswa ｐ",
    "ｐ a ｎ caｋｅｓｗａ ｐ",
    "ｐ a ｎ ｃakesｗａp",
    "ｐ ａ ｎ caｋｅsｗap",
    "pａ ｎ cａｋeswa ｐ",
    "ｐ ancakeswａp",
    "pa ｎ caｋesｗap",
    "pa ｎ ｃａkeｓｗa ｐ",
    "ｐ ａ ｎ ｃaｋesｗap",
    "ｐ a ｎ cakｅｓwap",
    "ｐ ａ ｎ ｃakｅswａ ｐ",
    "ｐ a ｎ cａｋeｓｗａ ｐ",
    "ｐ ａ ｎ cａｋeｓｗａ ｐ",
    "ｐ ａ ｎ cakeｓｗａ ｐ",
    "ｐ ancａｋeswａp",
    "ｐ a ｎ ｃａkｅsｗａp",
    "ｐ ａ ｎ ｃakeｓｗａp",
    "ｐ a ｎ ｃaｋｅｓｗａp",
    "ｐ anｃaｋｅswａp",
    "pａ ｎ cａｋｅsｗa ｐ",
    "ｐ ａncakｅｓｗａp",
    "ｐ ａncakeswap",
    "ｐ a ｎ ｃａkesｗap",
    "ｐ anｃａkｅsｗap",
    "pa ｎ cakｅｓwap",
    "pａ ｎ ｃakeｓwap",
    "ｐ a ｎ cａｋeswa ｐ",
    "ｐ ａncａｋｅｓｗａp",
    "pａ ｎ ｃａｋｅsｗap",
    "ｐ ａ ｎ cａkesｗa ｐ",
    "ｐ ａ ｎ ｃaｋｅsｗａp",
    "ｐ ａncａｋeｓwap",
    "ｐ ａncakesｗa ｐ",
    "pa ｎ ｃakｅsｗa ｐ",
    "ｐ anｃakesｗａ ｐ",
    "ｐ anｃａkeｓｗａp",
    "ｐ a ｎ caｋeswap",
    "pa ｎ caｋesｗａ ｐ",
    "pa ｎ ｃａkｅsｗａp",
    "ｐ ancaｋesｗap",
    "pa ｎ cakｅsｗa ｐ",
    "pａ ｎ ｃaｋｅswａ ｐ",
    "pａ ｎ cakeｓｗａp",
    "ｐ anｃａｋｅｓｗａp",
    "ｐ ancａkeｓwａ ｐ",
    "pa ｎ cａkeswa ｐ",
    "ｐ ａncａkeｓwap",
    "ｐ ａncａｋeswａ ｐ",
    "ｐ ａ ｎ cａｋesｗa ｐ",
    "ｐ ａ ｎ cａkesｗａp",
    "ｐ ａ ｎ cakｅｓｗａ ｐ",
    "ｐ anｃaｋeswa ｐ",
    "ｐ ａ ｎ caｋｅｓｗａ ｐ",
    "pａ ｎ cakeｓｗap",
    "ｐ anｃakｅｓwａ ｐ",
    "pａ ｎ cakｅｓwap",
    "pａ ｎ cａkｅswａ ｐ",
    "ｐ ancakｅｓwａ ｐ",
    "pa ｎ ｃａkｅsｗａ ｐ",
    "ｐ a ｎ cａｋesｗa ｐ",
    "ｐ ａnｃaｋesｗａ ｐ",
    "ｐ ａ ｎ ｃａｋｅｓwａ ｐ",
    "ｐ ａncaｋｅｓｗap",
    "ｐ anｃaｋeｓｗａp",
    "ｐ ａncakeｓｗap",
    "ｐ ａ ｎ cａkeｓｗap",
    "pａ ｎ cａkeｓwap",
    "ｐ a ｎ cａｋesｗap",
    "pａ ｎ caｋｅsｗap",
    "ｐ ａ ｎ ｃaｋｅｓｗａp",
    "ｐ a ｎ ｃａkeswa ｐ",
    "ｐ a ｎ ｃakｅｓｗap",
    "pａ ｎ cakｅｓｗap",
    "pa ｎ caｋeswａ ｐ",
    "ｐ ａ ｎ cａｋｅswa ｐ",
    "ｐ ａ ｎ caｋｅｓwａp",
    "pａ ｎ ｃakｅswap",
    "ｐ ａ ｎ ｃakeswａ ｐ",
    "ｐ ａnｃａｋｅｓｗa ｐ",
    "pａ ｎ cａkeswap",
    "ｐ ａ ｎ ｃakｅｓｗap",
    "ｐ a ｎ cakeｓwap",
    "pａ ｎ ｃａｋｅswａ ｐ",
    "ｐ ａnｃａｋesｗa ｐ",
    "ｐ ancaｋｅｓwａ ｐ",
    "pａ ｎ ｃakｅsｗａp",
    "ｐ ａ ｎ cａｋeｓｗａp",
    "ｐ a ｎ cａkeswap",
    "pａ ｎ cakesｗap",
    "ｐ ancａkesｗａ ｐ",
    "ｐ anｃakｅｓwa ｐ",
    "pa ｎ ｃaｋesｗa ｐ",
    "ｐ ａ ｎ ｃakesｗap",
    "ｐ ａ ｎ ｃａｋｅｓｗa ｐ",
    "ｐ ａnｃaｋeswap",
    "ｐ a ｎ cａkeｓｗa ｐ",
    "ｐ anｃaｋesｗａ ｐ",
    "pａ ｎ cａｋｅｓwap",
    "ｐ ａncａkｅswａp",
    "ｐ ａncａｋｅｓwap",
    "ｐ ａncaｋeｓｗa ｐ",
    "pａ ｎ cａkesｗａp",
    "ｐ ａ ｎ cａｋeｓwａ ｐ",
    "ｐ a ｎ cａｋｅswａ ｐ",
    "pa ｎ ｃａｋesｗａ ｐ",
    "ｐ ａncａｋeｓwａp",
    "pａ ｎ ｃａkeswa ｐ",
    "pa ｎ cａｋesｗa ｐ",
    "ｐ ａ ｎ ｃaｋｅｓｗａ ｐ",
    "ｐ ａncａｋｅｓｗａ ｐ",
    "ｐ a ｎ ｃaｋesｗap",
    "ｐ ａ ｎ ｃａｋｅsｗap",
    "pａ ｎ ｃaｋｅｓｗa ｐ",
    "ｐ ａ ｎ cａkｅｓwａ ｐ",
    "pa ｎ ｃakeｓwａp",
    "pａ ｎ caｋｅsｗa ｐ",
    "ｐ ａ ｎ ｃａｋeｓwａ ｐ",
    "pa ｎ ｃakｅｓｗａp",
    "ｐ ａnｃakeｓｗap",
    "ｐ anｃakesｗa ｐ",
    "ｐ a ｎ ｃａｋeｓｗａp",
    "pａ ｎ ｃakｅsｗa ｐ",
    "ｐ ａncａｋｅswa ｐ",
    "pa ｎ cａｋeｓwａ ｐ",
    "ｐ a ｎ cａkｅswa ｐ",
    "ｐ a ｎ ｃakesｗa ｐ",
    "ｐ a ｎ ｃakｅsｗa ｐ",
    "ｐ ａnｃａkｅｓwap",
    "pａ ｎ ｃａkeswａp",
    "pａ ｎ cａｋeｓwap",
    "ｐ ａnｃaｋｅsｗap",
    "ｐ ａncakｅswａ ｐ",
    "ｐ ａ ｎ ｃaｋeswa ｐ",
    "ｐ anｃaｋeswａp",
    "ｐ ａnｃａkｅswａ ｐ",
    "ｐ anｃａｋeswap",
    "ｐ a ｎ caｋeｓｗa ｐ",
    "ｐ a ｎ ｃaｋeｓwap",
    "ｐ ancａkｅｓｗa ｐ",
    "pａ ｎ cakｅsｗap",
    "ｐ ａ ｎ ｃakｅｓwａ ｐ",
    "ｐ a ｎ cakｅｓwａ ｐ",
    "ｐ anｃakｅsｗａ ｐ",
    "pａ ｎ ｃａｋｅｓwａ ｐ",
    "ｐ ａ ｎ cａｋｅsｗａ ｐ",
    "ｐ a ｎ cａｋｅｓwap",
    "ｐ ａnｃａkeswa ｐ",
    "ｐ ａnｃａkeｓwａp",
    "ｐ ａ ｎ ｃａｋeswａp",
    "pa ｎ cａkｅｓwａ ｐ",
    "pa ｎ ｃａｋeｓｗａp",
    "ｐ a ｎ ｃakeｓｗap",
    "ｐ ａ ｎ ｃaｋｅｓwap",
    "ｐ a ｎ cakeswａp",
    "pａ ｎ caｋｅswａ ｐ",
    "pａ ｎ ｃａｋeswap",
    "ｐ a ｎ ｃａkｅｓwａ ｐ",
    "pa ｎ cａkeｓwａp",
    "ｐ anｃａｋeｓｗａ ｐ",
    "ｐ a ｎ cａｋeｓwａ ｐ",
    "ｐ ａ ｎ caｋeswap",
    "ｐ a ｎ cａｋeｓwap",
    "ｐ anｃaｋeｓｗap",
    "pａ ｎ ｃaｋeｓwa ｐ",
    "ｐ a ｎ cａｋｅswａp",
    "ｐ ａ ｎ ｃaｋｅｓwa ｐ",
    "pa ｎ ｃakｅsｗａp",
    "pａ ｎ cａkesｗap",
    "ｐ ａ ｎ cａｋeｓｗap",
    "pa ｎ caｋeｓwa ｐ",
    "ｐ ａ ｎ cakｅｓｗａp",
    "ｐ ancａkeｓｗa ｐ",
    "ｐ a ｎ cａkesｗａ ｐ",
    "pａ ｎ ｃaｋeswａ ｐ",
    "pa ｎ cakesｗａp",
    "ｐ ancaｋｅsｗａ ｐ",
    "ｐ ancakｅｓwap",
    "ｐ a ｎ caｋｅswａp",
    "ｐ anｃａｋeｓwａp",
    "ｐ ａ ｎ ｃａｋeswa ｐ",
    "ｐ anｃakｅｓwap",
    "pa ｎ ｃakeswａp",
    "ｐ a ｎ ｃａkｅswａp",
    "pａ ｎ ｃaｋesｗａp",
    "ｐ ancaｋｅswap",
    "ｐ ａ ｎ cａkeｓｗa ｐ",
    "ｐ ａnｃａkeswap",
    "pａ ｎ ｃａkｅｓwａ ｐ",
    "ｐ ａncａkeswａp",
    "ｐ ａncａkｅsｗａ ｐ",
    "pa ｎ ｃakesｗａ ｐ",
    "ｐ ａncａｋeｓwａ ｐ",
    "pa ｎ ｃａｋｅswa ｐ",
    "pa ｎ ｃａｋeｓwa ｐ",
    "pａ ｎ ｃａｋｅｓｗap",
    "ｐ ａncaｋeｓｗａ ｐ",
    "ｐ anｃａｋesｗap",
    "ｐ a ｎ ｃakeswa ｐ",
    "pa ｎ ｃakeｓｗａp",
    "pa ｎ ｃakｅswap",
    "pａ ｎ ｃaｋｅsｗa ｐ",
    "pａ ｎ cａkｅｓwap",
    "ｐ anｃａｋeｓwa ｐ",
    "pａ ｎ ｃaｋeｓwａ ｐ",
    "pａ ｎ cakｅｓｗａp",
    "pa ｎ cａkesｗap",
    "ｐ a ｎ ｃakeswap",
    "pa ｎ ｃａkｅswａ ｐ",
    "ｐ ancaｋｅswａ ｐ",
    "ｐ a ｎ cakｅｓｗａp",
    "ｐ a ｎ cakｅｓｗａ ｐ",
    "ｐ ancａｋｅswａ ｐ",
    "ｐ ａnｃakｅｓwap",
    "ｐ ａncａｋeｓｗa ｐ",
    "pa ｎ cａｋesｗap",
    "pａ ｎ ｃａｋｅsｗa ｐ",
    "pa ｎ ｃaｋｅsｗa ｐ",
    "ｐ ａ ｎ cakｅsｗａp",
    "pａ ｎ ｃakesｗａ ｐ",
    "ｐ ａ ｎ ｃａkeｓwa ｐ",
    "pａ ｎ cakｅｓｗａ ｐ",
    "ｐ a ｎ ｃａkeswａ ｐ",
    "pa ｎ cakｅsｗａ ｐ",
    "ｐ anｃａkｅswａ ｐ",
    "ｐ ancaｋeｓwａp",
    "ｐ ａ ｎ cakｅsｗa ｐ",
    "ｐ ａncａkeｓwａ ｐ",
    "pa ｎ cakｅswap",
    "ｐ ａ ｎ ｃａkｅｓｗap",
    "ｐ ａnｃａkｅｓwａp",
    "ｐ ａ ｎ ｃａｋeswａ ｐ",
    "ｐ ａncａkeｓwa ｐ",
    "ｐ ａncakｅsｗa ｐ",
    "pａ ｎ cakｅswａp",
    "ｐ ａnｃａkeｓwa ｐ",
    "ｐ anｃａｋｅｓｗa ｐ",
    "pａ ｎ ｃａkeｓwａ ｐ",
    "ｐ ａnｃａｋｅsｗap",
    "ｐ ａncaｋesｗap",
    "ｐ ａncａｋｅswａp",
    "ｐ ａncaｋｅｓwa ｐ",
    "pａ ｎ caｋｅswap",
    "ｐ ａncａｋｅｓｗap",
    "ｐ anｃakeｓｗａp",
    "ｐ a ｎ caｋeｓwap",
    "pａ ｎ ｃａkｅｓｗap",
    "ｐ ａncaｋｅｓｗａ ｐ",
    "pａ ｎ caｋeｓwap",
    "ｐ ａ ｎ cａkeｓｗａ ｐ",
    "ｐ ａnｃaｋｅｓwap",
    "ｐ anｃａｋeswａp",
    "ｐ a ｎ cａkｅｓｗａp",
    "pａ ｎ cａｋesｗａp",
    "ｐ ａnｃakｅswap",
    "pａ ｎ ｃａｋeｓwａp",
    "ｐ ancａkｅｓwａp",
    "ｐ a ｎ ｃａｋeｓｗap",
    "ｐ a ｎ ｃａkeｓwa ｐ",
    "ｐ ａ ｎ ｃａｋeswap",
    "ｐ ａnｃaｋeswａp",
    "pa ｎ ｃａkeswａ ｐ",
    "ｐ ancakeｓｗａ ｐ",
    "pａ ｎ ｃakｅｓｗap",
    "pａ ｎ ｃａkｅsｗap",
    "ｐ ａnｃａkｅsｗａp",
    "ｐ ancａｋeswａ ｐ",
    "ｐ ａnｃaｋｅｓｗap",
    "ｐ ancａｋesｗa ｐ",
    "ｐ ａnｃａｋesｗap",
    "ｐ ａ ｎ cａkｅswap",
    "pａ ｎ cａkeｓwａp",
    "pａ ｎ cａｋｅｓwａ ｐ",
    "ｐ a ｎ ｃａｋｅsｗａp",
    "ｐ ancａｋeｓwａp",
    "ｐ ａnｃａｋeｓwa ｐ",
    "pa ｎ caｋesｗａp",
    "pa ｎ ｃａｋeｓwａ ｐ",
    "pa ｎ ｃakeｓｗａ ｐ",
    "ｐ ａnｃａｋｅswａp",
    "ｐ ancakｅｓwａp",
    "pａ ｎ cａkeswａp",
    "ｐ anｃakｅswa ｐ",
    "ｐ anｃａｋeｓｗap",
    "ｐ ａ ｎ caｋeｓｗａp",
    "pa ｎ caｋｅsｗａ ｐ",
    "ｐ ａ ｎ ｃａkｅswａp",
    "ｐ a ｎ ｃａkｅswａ ｐ",
    "ｐ ａ ｎ cakeｓｗap",
    "ｐ anｃａkｅｓwａ ｐ",
    "pａ ｎ cａkeｓwa ｐ",
    "ｐ anｃaｋｅｓｗａ ｐ",
    "pa ｎ cakeｓｗap",
    "ｐ a ｎ ｃａkeｓwap",
    "ｐ anｃakeｓwap",
    "ｐ a ｎ cａｋｅsｗａp",
    "ｐ ａ ｎ ｃａkｅｓｗａp",
    "pa ｎ ｃａｋeｓwap",
    "pａ ｎ ｃakeｓwａ ｐ",
    "pａ ｎ ｃａｋｅsｗａp",
    "ｐ ａnｃaｋeｓｗa ｐ",
    "ｐ ａnｃａkｅｓｗa ｐ",
    "pa ｎ ｃaｋｅｓｗａp",
    "pa ｎ cakｅｓwa ｐ",
    "ｐ ａnｃakeｓｗａ ｐ",
    "ｐ a ｎ cakeｓｗａp",
    "ｐ ａ ｎ ｃａｋeｓｗａp",
    "ｐ anｃakｅｓｗa ｐ",
    "ｐ ａncａkeｓｗａ ｐ",
    "pa ｎ ｃaｋeｓwa ｐ",
    "pa ｎ cａkeｓｗａ ｐ",
    "pａ ｎ cａkｅｓwａp",
    "ｐ ａncakesｗap",
    "ｐ ａ ｎ caｋesｗａ ｐ",
    "pａ ｎ ｃaｋｅswａp",
    "ｐ ａncａｋeｓｗap",
    "pａ ｎ ｃａkｅｓｗa ｐ",
    "pａ ｎ caｋesｗａp",
    "ｐ a ｎ cａkｅｓwａ ｐ",
    "ｐ ａ ｎ cakeｓｗa ｐ",
    "ｐ ａncａkｅsｗａp",
    "ｐ ancaｋｅｓｗａp",
    "ｐ ａ ｎ ｃａkｅｓwap",
    "pa ｎ ｃaｋｅswa ｐ",
    "pa ｎ cａｋｅsｗa ｐ",
    "ｐ a ｎ cａｋeｓｗａp",
    "pａ ｎ cakeｓｗa ｐ",
    "pａ ｎ ｃaｋｅｓｗap",
    "pa ｎ ｃaｋeswap",
    "ｐ a ｎ caｋesｗａ ｐ",
    "ｐ a ｎ ｃaｋｅｓｗap",
    "pａ ｎ cakｅｓwａ ｐ",
    "ｐ ａncａkｅｓwap",
    "ｐ a ｎ ｃakeｓwa ｐ",
    "ｐ a ｎ cakｅswap",
    "ｐ a ｎ cａｋｅswap",
    "ｐ a ｎ cａkｅsｗａp",
    "ｐ ａncakｅswap",
    "pa ｎ caｋｅｓwａ ｐ",
    "ｐ a ｎ cａkeｓｗａ ｐ",
    "pa ｎ ｃakｅｓwａp",
    "ｐ anｃaｋesｗａp",
    "pａ ｎ ｃａkeｓwap",
    "ｐ ａnｃａｋｅｓｗａ ｐ",
    "pａ ｎ ｃaｋesｗａ ｐ",
    "ｐ a ｎ ｃａkeｓwａp",
    "pａ ｎ cａｋｅswap",
    "ｐ ａ ｎ ｃａkｅsｗa ｐ",
    "ｐ ａncakｅsｗａp",
    "ｐ ａnｃａkｅsｗａ ｐ",
    "pａ ｎ cａｋeｓwａ ｐ",
    "ｐ ancakesｗａp",
    "ｐ ａ ｎ caｋｅｓｗap",
    "ｐ anｃakｅｓwａp",
    "ｐ ancａkｅsｗa ｐ",
    "ｐ ancａｋｅｓｗap",
    "pa ｎ caｋｅsｗａp",
    "ｐ ancａｋeｓｗap",
    "ｐ a ｎ cａkesｗａp",
    "pa ｎ cａkeswａ ｐ",
    "pa ｎ cａｋｅsｗａ ｐ",
    "pa ｎ caｋeswａp",
    "ｐ ａ ｎ caｋｅｓｗａp",
    "ｐ ａ ｎ ｃaｋeｓｗap",
    "ｐ ａncaｋeｓｗap",
    "pa ｎ ｃａkｅｓｗａ ｐ",
    "pa ｎ cａｋeｓｗａ ｐ",
    "ｐ ａ ｎ cａkｅｓｗａ ｐ",
    "ｐ ａ ｎ ｃａｋeｓwap",
    "ｐ ａncａkeswa ｐ",
    "ｐ ａ ｎ ｃakｅｓｗａp",
    "ｐ ａ ｎ ｃaｋeｓwa ｐ",
    "ｐ ancakｅswａ ｐ",
    "ｐ ａncaｋeswa ｐ",
    "pａ ｎ ｃａｋeswａ ｐ",
    "ｐ anｃａkｅswa ｐ",
    "ｐ ａnｃaｋeｓwap",
    "pａ ｎ ｃａkeｓｗap",
    "ｐ a ｎ ｃａｋｅswa ｐ",
    "pa ｎ ｃａｋesｗａp",
    "ｐ ancaｋｅswａp",
    "ｐ a ｎ ｃaｋｅsｗａp",
    "pａ ｎ ｃaｋｅsｗap",
    "ｐ ａncａkｅsｗa ｐ",
    "ｐ ａnｃａｋｅsｗa ｐ",
    "pａ ｎ cａkesｗa ｐ",
    "ｐ a ｎ caｋesｗap",
    "pa ｎ ｃakｅswａ ｐ",
    "pａ ｎ ｃakeswａp",
    "ｐ a ｎ cakesｗａ ｐ",
    "pａ ｎ cakeｓwａ ｐ",
    "ｐ ａ ｎ cａkｅsｗａp",
    "ｐ ａ ｎ ｃａkeｓwａp",
    "ｐ a ｎ cakｅsｗa ｐ",
    "ｐ a ｎ cakｅｓｗap",
    "ｐ ａ ｎ ｃaｋｅｓｗap",
    "pa ｎ ｃakesｗａp",
    "ｐ a ｎ cａkeｓｗａp",
    "ｐ a ｎ ｃakesｗａ ｐ",
    "ｐ a ｎ ｃakｅｓwap",
    "ｐ anｃａkｅｓｗａ ｐ",
    "ｐ a ｎ caｋｅswap",
    "ｐ a ｎ cａkｅｓｗａ ｐ",
    "pａ ｎ ｃakesｗａp",
    "ｐ ａnｃaｋｅｓｗａp",
    "ｐ ａncaｋeｓwａ ｐ",
    "ｐ anｃaｋｅｓwa ｐ",
    "ｐ ancａｋeｓwａ ｐ",
    "ｐ anｃakeｓｗａ ｐ",
    "pa ｎ cａｋｅｓｗap",
    "ｐ ancaｋｅｓwap",
    "ｐ a ｎ ｃaｋesｗａ ｐ",
    "ｐ ancaｋesｗa ｐ",
    "pａ ｎ ｃaｋｅｓwa ｐ",
    "ｐ ａncakeswａ ｐ",
    "ｐ a ｎ cａｋｅｓwａp",
    "ｐ a ｎ ｃａｋｅｓｗａp",
    "pａ ｎ cakeｓｗａ ｐ",
    "ｐ ancakesｗa ｐ",
    "pａ ｎ cａkｅｓwa ｐ",
    "ｐ ａnｃaｋeｓｗａp",
    "ｐ ａnｃakesｗａ ｐ",
    "ｐ a ｎ caｋｅsｗａp",
    "ｐ ａ ｎ cａｋｅｓｗａp",
    "pa ｎ cakeswa ｐ",
    "ｐ ａ ｎ cakｅswa ｐ",
    "ｐ ancａkeｓｗａ ｐ",
    "ｐ ａ ｎ ｃａｋｅsｗａ ｐ",
    "ｐ ａnｃaｋｅsｗａ ｐ",
    "ｐ ａ ｎ cａkｅｓwａp",
    "ｐ ancaｋｅsｗa ｐ",
    "ｐ a ｎ ｃａｋeｓwap",
    "pａ ｎ ｃａkeｓｗａ ｐ",
    "ｐ ａ ｎ ｃaｋｅswap",
    "ｐ a ｎ ｃaｋeｓｗap",
    "ｐ ａ ｎ cａｋｅｓｗap",
    "ｐ ａ ｎ cａkeswａ ｐ",
    "ｐ ａ ｎ cakｅｓwａp",
    "ｐ ａnｃａｋeｓwap",
    "pａ ｎ caｋeswa ｐ",
    "pａ ｎ ｃａkｅswa ｐ",
    "pa ｎ ｃakeｓwap",
    "pａ ｎ ｃａkｅsｗａp",
    "pa ｎ cａｋｅswa ｐ",
    "pａ ｎ ｃａｋｅｓｗａ ｐ",
    "pａ ｎ caｋeｓｗａ ｐ",
    "ｐ ancａｋeｓwap",
    "pa ｎ ｃａｋｅｓｗａp",
    "ｐ a ｎ cａkｅｓwａp",
    "pa ｎ ｃａkｅｓｗa ｐ",
    "pａ ｎ ｃakeswa ｐ",
    "pａ ｎ ｃａkｅｓwap",
    "ｐ ａncaｋeｓwａp",
    "ｐ ａncaｋeｓwap",
    "ｐ ancａｋesｗａ ｐ",
    "ｐ a ｎ cakesｗap",
    "ｐ ａ ｎ cakｅｓwa ｐ",
    "ｐ ａ ｎ caｋeｓwap",
    "ｐ a ｎ ｃaｋｅswａ ｐ",
    "pａ ｎ cａｋｅswａ ｐ",
    "pａ ｎ ｃａkｅswａ ｐ",
    "ｐ ａ ｎ cakｅswａp",
    "ｐ a ｎ cａkesｗa ｐ",
    "ｐ ａ ｎ cakeswap",
    "ｐ ａ ｎ ｃａkｅswap",
    "pa ｎ ｃａkeｓwap",
    "pａ ｎ ｃａkesｗap",
    "ｐ ancａkｅswａ ｐ",
    "ｐ ａnｃaｋｅｓｗa ｐ",
    "ｐ ａnｃａｋeswa ｐ",
    "pａ ｎ cakｅｓwａp",
    "ｐ a ｎ caｋｅｓwap",
    "ｐ a ｎ cａｋｅsｗa ｐ",
    "pa ｎ ｃakｅsｗap",
    "ｐ anｃａｋｅswa ｐ",
    "pa ｎ ｃａkｅｓｗap",
    "pa ｎ caｋｅswａ ｐ",
    "pａ ｎ cakeｓwａp",
    "ｐ a ｎ ｃaｋeswa ｐ",
    "ｐ anｃaｋｅswap",
    "ｐ ancakｅswａp",
    "pa ｎ cａｋeｓwａp",
    "ｐ ａ ｎ cａkｅsｗａ ｐ",
    "pａ ｎ caｋeswap",
    "ｐ a ｎ cａkｅswap",
    "ｐ anｃaｋｅｓwap",
    "ｐ ａncaｋeswａ ｐ",
    "ｐ anｃａｋｅswａ ｐ",
    "ｐ ancaｋｅｓwa ｐ",
    "pa ｎ cakｅｓｗa ｐ",
    "ｐ anｃakｅswａ ｐ",
    "ｐ anｃａkeｓwa ｐ",
    "pa ｎ cａkｅｓwa ｐ",
    "pａ ｎ ｃaｋeｓｗap",
    "ｐ a ｎ ｃaｋｅｓwａ ｐ",
    "pａ ｎ cａkeｓwａ ｐ",
    "pa ｎ cakeｓｗa ｐ",
    "ｐ a ｎ ｃａｋｅｓｗa ｐ",
    "pａ ｎ ｃakｅｓｗａp",
    "pa ｎ caｋeｓｗａ ｐ",
    "ｐ a ｎ caｋｅsｗａ ｐ",
    "ｐ ancａｋｅswap",
    "ｐ ａncakeｓwａ ｐ",
    "ｐ ａ ｎ caｋｅswａ ｐ",
    "ｐ ａ ｎ cａkｅｓｗａp",
    "pa ｎ cakeswａ ｐ",
    "pａ ｎ ｃakｅｓwａp",
    "ｐ ancakeswａ ｐ",
    "ｐ ａnｃａkｅsｗap",
    "ｐ ａ ｎ ｃakeｓwap",
    "pa ｎ ｃakeswa ｐ",
    "ｐ a ｎ ｃaｋeswａp",
    "ｐ ａnｃaｋeｓwａ ｐ",
    "pａ ｎ ｃａｋｅｓwa ｐ",
    "ｐ ａ ｎ cａkｅｓwa ｐ",
    "ｐ ａ ｎ cａｋeswa ｐ",
    "ｐ a ｎ ｃａｋeswa ｐ",
    "ｐ ａ ｎ caｋeｓwａp",
    "ｐ ａncａｋｅｓwa ｐ",
    "ｐ ａnｃａkｅswａp",
    "ｐ ａnｃakｅｓｗap",
    "ｐ ａnｃａkeswａp",
    "ｐ ａnｃａｋｅsｗａp",
    "pa ｎ ｃａkｅsｗap",
    "ｐ anｃａｋesｗａp",
    "pa ｎ caｋｅsｗap",
    "ｐ ａ ｎ ｃaｋeswap",
    "ｐ anｃaｋｅｓwａp",
    "ｐ ａnｃaｋeｓｗap",
    "ｐ ａncaｋｅsｗａ ｐ",
    "ｐ anｃaｋｅｓｗａp",
    "pａ ｎ cａkｅswａp",
    "pa ｎ ｃａｋｅｓｗap",
    "ｐ a ｎ ｃaｋｅswa ｐ",
    "ｐ ａnｃａkｅｓｗａp",
    "ｐ ancａｋｅsｗａp",
    "ｐ a ｎ ｃａkesｗａ ｐ",
    "pa ｎ ｃａｋｅswap",
    "ｐ anｃａｋeswａ ｐ",
    "ｐ ａ ｎ cakeswａ ｐ",
    "pa ｎ cａkｅswa ｐ",
    "ｐ a ｎ ｃaｋｅsｗａ ｐ",
    "ｐ ａ ｎ cakeｓwａ ｐ",
    "ｐ a ｎ caｋｅsｗa ｐ",
    "ｐ ancaｋeswａ ｐ",
    "ｐ a ｎ caｋｅsｗap",
    "ｐ ａncａkｅｓｗａ ｐ",
    "ｐ anｃａｋｅsｗa ｐ",
    "pa ｎ cａｋｅswａp",
    "pa ｎ cａｋesｗａp",
    "ｐ ａ ｎ ｃakeｓwａp",
    "ｐ ａnｃaｋeswａ ｐ",
    "ｐ ａnｃａkesｗａ ｐ",
    "ｐ a ｎ caｋeｓwａp",
    "pａ ｎ ｃakｅｓｗａ ｐ",
    "ｐ ａ ｎ cakeswa ｐ",
    "ｐ ancaｋeｓwa ｐ",
    "ｐ ａ ｎ ｃaｋeｓwap",
    "pa ｎ ｃakeｓｗa ｐ",
    "ｐ a ｎ ｃakｅsｗａp",
    "pa ｎ caｋｅsｗa ｐ",
    "pa ｎ cａkｅｓwａp",
    "ｐ ａnｃａkesｗap",
    "ｐ ancａｋeｓｗａp",
    "ｐ a ｎ ｃakeｓｗａp",
    "pa ｎ cakeswap",
    "ｐ ancａｋｅｓwａp",
    "pa ｎ cakeswａp",
    "ｐ ａnｃakｅswａ ｐ",
    "ｐ a ｎ caｋeswa ｐ",
    "ｐ anｃakｅswａp",
    "pa ｎ ｃａｋｅｓｗａ ｐ",
    "pa ｎ ｃａkeｓwa ｐ",
    "pａ ｎ ｃａｋeｓｗａ ｐ",
    "ｐ ａncaｋｅsｗａp",
    "ｐ ａnｃａkeｓｗa ｐ",
    "pａ ｎ ｃａｋｅｓｗa ｐ",
    "ｐ ａ ｎ cakｅswap",
    "ｐ a ｎ cａkｅｓwa ｐ",
    "ｐ ａ ｎ ｃａｋｅｓｗap",
    "ｐ ａ ｎ cakesｗap",
    "ｐ ancａkｅswa ｐ",
    "ｐ ａ ｎ cａｋｅswａp",
    "pａ ｎ ｃaｋeswa ｐ",
    "ｐ ａ ｎ ｃakｅsｗap",
    "ｐ a ｎ cａkｅｓｗa ｐ",
    "ｐ ａ ｎ cａkeｓｗａp",
    "ｐ ａ ｎ cakesｗa ｐ",
    "ｐ anｃａｋｅsｗａp",
    "pａ ｎ caｋeｓｗa ｐ",
    "ｐ a ｎ ｃａkｅｓｗap",
    "ｐ ａncaｋesｗa ｐ",
    "ｐ a ｎ cakｅswａ ｐ",
    "pa ｎ ｃａｋｅｓwａ ｐ",
    "ｐ ａnｃakeｓwa ｐ",
    "ｐ ａncaｋｅｓwap",
    "ｐ a ｎ ｃａkeｓｗａ ｐ",
    "ｐ ａnｃaｋesｗa ｐ",
    "ｐ ａ ｎ ｃａkeｓwap",
    "ｐ anｃａkeswa ｐ",
    "ｐ a ｎ ｃakｅｓｗａ ｐ",
    "ｐ ａ ｎ cａｋeswａ ｐ",
    "pａ ｎ cakeswap",
    "ｐ ancａｋｅsｗａ ｐ",
    "ｐ ａ ｎ ｃａｋｅswa ｐ",
    "pa ｎ caｋｅswap",
    "pａ ｎ ｃakeｓｗａp",
    "ｐ a ｎ ｃａｋeｓｗａ ｐ",
    "pａ ｎ cakeswａ ｐ",
    "ｐ ａ ｎ ｃaｋeｓｗａp",
    "ｐ ａnｃａkeｓwap",
    "ｐ a ｎ ｃａkｅｓｗａp",
    "ｐ ａ ｎ caｋeｓwa ｐ",
    "pa ｎ ｃａkｅswａp",
    "ｐ a ｎ ｃａkeswａp",
    "pａ ｎ ｃaｋｅswa ｐ",
    "ｐ anｃaｋeｓwａ ｐ",
    "ｐ anｃａｋesｗa ｐ",
    "ｐ ancakeｓｗａp",
    "pａ ｎ cakｅｓｗa ｐ",
    "ｐ a ｎ cａkesｗap",
    "ｐ anｃakｅswap",
    "ｐ ａ ｎ cａｋｅswａ ｐ",
    "ｐ ａncａkeｓｗap",
    "ｐ ａ ｎ caｋeswa ｐ",
    "pａ ｎ ｃaｋｅsｗａ ｐ",
    "ｐ ａ ｎ cａｋｅsｗa ｐ",
    "ｐ ａncａkｅｓｗa ｐ",
    "pa ｎ ｃakeswａ ｐ",
    "ｐ anｃakｅｓｗａp",
    "pa ｎ cａｋeswａ ｐ",
    "ｐ ancaｋｅｓwａp",
    "ｐ ａ ｎ ｃａkeswａ ｐ",
    "pａ ｎ ｃakｅｓwa ｐ",
    "ｐ ａncaｋｅｓwａ ｐ",
    "pａ ｎ cａｋeｓwa ｐ",
    "pa ｎ cａｋeswa ｐ",
    "ｐ anｃａkｅｓwａp",
    "ｐ ａnｃａkeｓwａ ｐ",
    "ｐ a ｎ ｃａｋｅｓｗap",
    "ｐ ａ ｎ ｃａｋesｗａ ｐ",
    "pa ｎ cａkｅsｗap",
    "ｐ anｃａkｅsｗａ ｐ",
    "ｐ ａncaｋｅｓｗa ｐ",
    "pａ ｎ cａkｅｓｗａ ｐ",
    "ｐ ａ ｎ cakｅｓｗa ｐ",
    "pa ｎ ｃakesｗap",
    "pa ｎ cａｋｅswap",
    "ｐ ａnｃaｋeswa ｐ",
    "ｐ ａnｃakeｓwａ ｐ",
    "ｐ ａ ｎ cａkeｓwap",
    "ｐ ａ ｎ ｃａｋｅｓｗａ ｐ",
    "ｐ ａ ｎ ｃaｋeｓｗａ ｐ",
    "ｐ ａ ｎ ｃａｋesｗａp",
    "ｐ a ｎ ｃakeｓｗａ ｐ",
    "pａ ｎ cａkｅswa ｐ",
    "ｐ a ｎ ｃakeswａ ｐ",
    "ｐ anｃａｋｅｓwａ ｐ",
    "pa ｎ ｃaｋｅｓwap",
    "ｐ ａncaｋｅswａ ｐ",
    "ｐ a ｎ cakｅｓwa ｐ",
    "ｐ ａncａｋｅswａ ｐ",
    "pa ｎ ｃakeｓwａ ｐ",
    "ｐ ａncakesｗａp",
    "ｐ ａnｃakeｓwap",
    "ｐ ａ ｎ ｃａkeｓｗａp",
    "ｐ ａ ｎ cａｋｅsｗａp",
    "ｐ ａncakeｓwａp",
    "pa ｎ cａkeｓwa ｐ",
    "ｐ anｃａｋｅsｗａ ｐ",
    "pａ ｎ ｃａkｅｓwａp",
    "ｐ ａ ｎ cakｅsｗap",
    "pa ｎ cａkｅsｗａp",
    "ｐ a ｎ ｃａkｅｓwap",
    "ｐ ａ ｎ ｃａkｅswa ｐ",
    "ｐ ancａｋｅｓwａ ｐ",
    "ｐ ａ ｎ cａｋeｓｗa ｐ",
    "pａ ｎ ｃａkeswａ ｐ",
    "ｐ ａnｃakｅｓｗａp",
    "pa ｎ ｃａkesｗap",
    "ｐ anｃａkｅｓwa ｐ",
    "pa ｎ ｃakｅsｗａ ｐ",
    "ｐ ａnｃａkｅｓwａ ｐ",
    "ｐ ａ ｎ cａkｅswa ｐ",
    "ｐ ａnｃakｅｓwａp",
    "pa ｎ ｃａｋｅｓwap",
    "ｐ ａnｃaｋｅｓwａ ｐ",
    "ｐ anｃaｋｅｓｗa ｐ",
    "ｐ a ｎ ｃａkｅsｗａ ｐ",
    "ｐ ancａkeswa ｐ",
    "pａ ｎ ｃakeｓｗa ｐ",
    "pａ ｎ caｋｅｓwａ ｐ",
    "ｐ a ｎ caｋｅｓwａp",
    "ｐ ancａkesｗap",
    "ｐ anｃａkeｓwap",
    "ｐ ａ ｎ ｃａkｅｓｗａ ｐ",
    "ｐ ancaｋｅｓｗa ｐ",
    "ｐ ａ ｎ ｃakeswａp",
    "pa ｎ ｃaｋｅｓwａ ｐ",
    "pａ ｎ cａkeｓｗap",
    "ｐ ａ ｎ ｃａkeｓwａ ｐ",
    "ｐ ancａｋｅswａp",
    "ｐ ａnｃａｋeswａp",
    "pａ ｎ caｋesｗap",
    "pａ ｎ cａｋeswａ ｐ",
    "ｐ ａncaｋeｓｗａp",
    "pa ｎ ｃaｋesｗａp",
    "ｐ ａnｃaｋｅswap",
    "pa ｎ ｃaｋeｓwap",
    "pａ ｎ ｃaｋｅｓｗａ ｐ",
    "ｐ ａncaｋeswａp",
    "ｐ a ｎ cakeｓwa ｐ",
    "pa ｎ ｃａkesｗａ ｐ",
    "ｐ ａ ｎ ｃakｅsｗa ｐ",
    "pａ ｎ ｃａkｅsｗa ｐ",
    "ｐ anｃaｋｅsｗap",
    "pａ ｎ ｃａｋeｓｗa ｐ",
    "ｐ a ｎ cａｋesｗａ ｐ",
    "pa ｎ cａkｅsｗａ ｐ",
    "ｐ ａnｃakeｓｗa ｐ",
    "ｐ ａncａkeswａ ｐ",
    "ｐ ａ ｎ ｃakｅswa ｐ",
    "pａ ｎ ｃａｋesｗap",
    "pａ ｎ cakesｗａp",
    "ｐ ancａｋｅsｗap",
    "ｐ ancaｋｅswa ｐ",
    "ｐ ancａkｅｓwa ｐ",
    "ｐ ancakｅswap",
    "pa ｎ cａkesｗa ｐ",
    "ｐ ancakesｗａ ｐ",
    "ｐ ａncａｋeswａp",
    "ｐ anｃakesｗａp",
    "ｐ ancaｋｅsｗａp",
    "ｐ a ｎ cａｋeswap",
    "ｐ a ｎ cａkｅsｗap",
    "ｐ ａ ｎ cａkeswap",
    "ｐ anｃakeswap",
    "ｐ a ｎ ｃaｋｅｓｗａ ｐ",
    "ｐ a ｎ cakｅswａp",
    "ｐ ａncakｅｓwａ ｐ",
    "ｐ ａ ｎ cａｋesｗａ ｐ",
    "ｐ ａ ｎ ｃaｋｅswａp",
    "ｐ ａncａｋeswap",
    "ｐ ａ ｎ cａkｅsｗa ｐ",
    "ｐ ａnｃａkｅsｗa ｐ",
    "pa ｎ cａkeｓwap",
    "ｐ ａncａkｅswａ ｐ",
    "ｐ ａ ｎ ｃａkｅswａ ｐ",
    "pa ｎ ｃaｋesｗａ ｐ",
    "ｐ a ｎ ｃａｋｅswａp",
    "ｐ ａncakeｓwa ｐ",
    "ｐ ａncａkesｗap",
    "ｐ a ｎ cａkｅｓｗap",
    "ｐ ａ ｎ ｃａkeｓｗap",
    "ｐ ａnｃaｋesｗap",
    "pa ｎ ｃakｅswａp",
    "ｐ ancaｋeswa ｐ",
    "ｐ anｃａkeｓｗap",
    "ｐ anｃakｅｓｗａ ｐ",
    "ｐ ａ ｎ ｃａkesｗａ ｐ",
    "pa ｎ ｃakｅｓｗａ ｐ",
    "pａ ｎ cakｅsｗａp",
    "pａ ｎ caｋｅｓｗａp",
    "ｐ ａ ｎ ｃａｋeｓｗa ｐ",
    "ｐ ancakｅｓｗa ｐ",
    "pa ｎ caｋｅｓwa ｐ",
    "ｐ ａ ｎ ｃａkeｓｗa ｐ",
    "ｐ a ｎ ｃaｋeｓwａp",
    "ｐ ａnｃａｋeｓｗａ ｐ",
    "pａ ｎ cａｋeｓｗa ｐ",
    "pa ｎ ｃａｋesｗap",
    "ｐ ａnｃakesｗａp",
    "pa ｎ ｃaｋeｓｗa ｐ",
    "pａ ｎ ｃａｋｅｓwap",
    "ｐ ａncakｅｓｗａ ｐ",
    "ｐ ａ ｎ cａｋeｓwa ｐ",
    "pａ ｎ ｃaｋeｓwａp",
    "ｐ ａ ｎ cａｋeswａp",
    "ｐ ａ ｎ ｃａｋｅｓwａp",
    "ｐ anｃａkｅswａp",
    "ｐ ａ ｎ caｋeswａ ｐ",
    "ｐ ａ ｎ caｋeｓwａ ｐ",
    "ｐ a ｎ cａｋｅｓｗａp",
    "pａ ｎ cａｋｅｓｗap",
    "pａ ｎ ｃaｋeｓｗａp",
    "pa ｎ cａｋｅｓwa ｐ",
    "ｐ a ｎ caｋeｓwａ ｐ",
    "pa ｎ cａｋeｓｗap",
    "ｐ anｃaｋeｓwａp",
    "ｐ a ｎ ｃａkeｓｗap",
    "pa ｎ ｃａｋeswap",
    "pa ｎ ｃakｅswa ｐ",
    "ｐ ａncakesｗａ ｐ",
    "ｐ anｃａkeswａ ｐ",
    "ｐ ａ ｎ cａkeswa ｐ",
    "pa ｎ cａｋｅsｗap",
    "ｐ ａncaｋｅswap",
    "ｐ a ｎ ｃａｋeｓｗa ｐ",
    "ｐ a ｎ cakeｓｗa ｐ",
    "ｐ ancａkeswａ ｐ",
    "pa ｎ ｃaｋeｓwａ ｐ",
    "ｐ anｃａｋeｓｗａp",
    "pa ｎ ｃａkｅｓwａ ｐ",
    "ｐ anｃakeｓｗap",
    "pａ ｎ cａkｅsｗａ ｐ",
    "pa ｎ cakｅswａp",
    "ｐ ａnｃａｋeｓｗa ｐ",
    "pa ｎ caｋｅｓwａp",
    "ｐ a ｎ cａｋｅsｗａ ｐ",
    "ｐ ａncａkｅｓｗａp",
    "pａ ｎ cakeｓwap",
    "pａ ｎ cａｋｅｓwa ｐ",
    "pａ ｎ ｃakeｓｗap",
    "ｐ ａnｃakｅsｗａ ｐ",
    "ｐ ａ ｎ ｃaｋｅsｗａ ｐ",
    "ｐ ａ ｎ ｃakｅsｗａ ｐ",
    "ｐ ａnｃａｋｅｓｗap",
    "ｐ ａnｃaｋｅsｗa ｐ",
    "ｐ a ｎ cａｋｅｓｗap",
    "ｐ ａncaｋｅsｗa ｐ",
    "ｐ ａ ｎ cａｋeswap",
    "pａ ｎ ｃａkｅｓwa ｐ",
    "pａ ｎ cａkｅswap",
    "ｐ a ｎ ｃakｅswap",
    "ｐ ａnｃaｋeｓwa ｐ",
    "ｐ ａnｃaｋeｓｗａ ｐ",
    "ｐ ancａｋｅｓwa ｐ",
    "ｐ ａncａｋｅsｗａp",
    "ｐ ａnｃakｅswａp",
    "pa ｎ ｃakｅｓwａ ｐ",
    "pa ｎ cakesｗap",
    "ｐ a ｎ caｋeｓｗａp",
    "ｐ a ｎ ｃａkesｗａp",
    "ｐ ａncａkｅswap",
    "ｐ ａ ｎ ｃakｅswａp",
    "ｐ a ｎ cakeｓwａp",
];

const listToClear = [
    "pａncakｅsｗap",
    "pａnｃａｋesｗa ｐ",
    "pａnｃaｋｅｓwa ｐ",
    "pancａkｅswa ｐ",
    "pancａkeｓｗａ ｐ",
    "pancaｋｅswa ｐ",
    "pａnｃaｋｅｓｗa ｐ",
    "panｃakeｓwａp",
    "pａncakeswａ ｐ",
    "pａncaｋｅsｗａp",
    "pａncａｋｅsｗａp",
    "panｃaｋesｗａp",
    "pａnｃaｋｅsｗap",
    "pａnｃakｅｓwa ｐ",
    "pａncakeｓｗap",
    "pａnｃaｋeｓwａp",
    "pａncａkｅｓｗａp",
    "panｃaｋｅｓｗａp",
    "pａncａkeｓｗa ｐ",
    "pａnｃaｋｅswap",
    "pａnｃａｋeswａ ｐ",
    "pａncakeswａp",
    "pancａkeｓｗap",
    "pａnｃakｅｓwap",
    "pａncａｋｅｓｗa ｐ",
    "panｃａkeｓｗａp",
    "pａnｃakeｓwａ ｐ",
    "pancａｋｅsｗａ ｐ",
    "pａncakeｓwa ｐ",
    "pancakｅｓｗａ ｐ",
    "pａncａkｅｓwa ｐ",
    "pａncaｋeｓｗａ ｐ",
    "panｃａｋesｗap",
    "pａnｃakesｗap",
    "pancaｋeｓwａ ｐ",
    "pａnｃａkeswap",
    "pａnｃakｅsｗａp",
    "pａncａkeｓwa ｐ",
    "pａncaｋeｓｗa ｐ",
    "pancａkｅｓｗap",
    "panｃａｋeｓｗa ｐ",
    "panｃａkｅsｗａp",
    "pａncａｋesｗap",
    "pancakeｓwａp",
    "pancａkｅswａp",
    "pａnｃakｅｓｗａ ｐ",
    "pａnｃaｋeｓｗa ｐ",
    "pａncaｋｅｓwa ｐ",
    "panｃakｅswａ ｐ",
    "pａncａｋｅsｗap",
    "pａnｃａkeｓwａ ｐ",
    "pancaｋｅｓwa ｐ",
    "pａncａｋeswa ｐ",
    "pａnｃａｋeｓwa ｐ",
    "pａnｃakeswａ ｐ",
    "panｃaｋｅｓｗａ ｐ",
    "pａnｃａｋｅsｗap",
    "pａnｃaｋｅsｗａp",
    "pancaｋｅｓｗa ｐ",
    "pａncakｅｓwa ｐ",
    "panｃａkesｗａ ｐ",
    "pａncaｋｅｓｗａp",
    "pａncａkeｓｗap",
    "pａncakｅsｗa ｐ",
    "pａnｃakｅswap",
    "pａnｃaｋeｓｗａp",
    "pａncakｅｓｗap",
    "panｃａｋesｗａp",
    "pancaｋesｗap",
    "pancaｋeｓｗａp",
    "panｃaｋｅswa ｐ",
    "pａncａkｅsｗa ｐ",
    "pａncakｅswａp",
    "pａnｃａkｅｓwａ ｐ",
    "pancａｋｅｓｗa ｐ",
    "pａncａkeｓｗａ ｐ",
    "pａnｃａｋesｗａ ｐ",
    "pancakeswap",
    "pａnｃakeｓｗap",
    "panｃakｅsｗａp",
    "pancａkeｓwａp",
    "panｃａｋeswａ ｐ",
    "panｃaｋeｓwa ｐ",
    "pancaｋeswap",
    "panｃaｋeｓｗａp",
    "panｃakｅswａp",
    "pancａkesｗａ ｐ",
    "pａnｃaｋｅｓｗap",
    "pａncａkｅsｗap",
    "panｃaｋeswap",
    "pancaｋｅsｗａ ｐ",
    "pancakｅsｗａ ｐ",
    "pａnｃakｅswａp",
    "pａnｃaｋeｓwａ ｐ",
    "pａncaｋesｗap",
    "pａnｃａｋｅswａp",
    "pａnｃaｋｅsｗa ｐ",
    "pａnｃaｋｅsｗａ ｐ",
    "panｃａkeswａ ｐ",
    "pａncａｋeswap",
    "panｃakeswａ ｐ",
    "pａnｃａｋｅｓwａp",
    "pancakｅswａp",
    "pancakesｗａp",
    "panｃaｋｅsｗａ ｐ",
    "pancａkeｓwa ｐ",
    "pancａkｅｓwａp",
    "pａnｃaｋｅswａp",
    "pancaｋｅｓｗap",
    "pancａｋｅｓｗap",
    "pancａｋeｓｗa ｐ",
    "pancａｋｅｓwa ｐ",
    "pａnｃａｋeswa ｐ",
    "pancaｋｅｓｗａp",
    "panｃaｋeｓｗap",
    "pａncakeswap",
    "pancａｋｅｓwap",
    "pａnｃaｋeｓｗａ ｐ",
    "pａnｃakｅｓｗap",
    "panｃａkｅｓｗap",
    "pancakeｓｗａ ｐ",
    "panｃａkeswap",
    "pａnｃaｋｅswａ ｐ",
    "pａnｃａｋｅswap",
    "panｃａｋeｓｗap",
    "pancakeｓｗap",
    "pａncakｅsｗａ ｐ",
    "pancａｋｅｓwａp",
    "pａncaｋeｓｗap",
    "pancakｅｓwａ ｐ",
    "pancaｋｅswａp",
    "pａncaｋeｓwａ ｐ",
    "pａncaｋｅｓｗａ ｐ",
    "panｃａkｅｓｗａp",
    "pａnｃaｋeｓｗap",
    "pａncakｅｓwａ ｐ",
    "pancａｋｅｓｗａ ｐ",
    "pａnｃakｅsｗap",
    "pａncakeｓｗａ ｐ",
    "panｃaｋｅsｗａp",
    "panｃakｅsｗap",
    "pancａkesｗa ｐ",
    "panｃａｋｅｓwap",
    "pancaｋesｗa ｐ",
    "pａnｃａkeｓwａp",
    "pａncaｋｅｓwap",
    "pａnｃａkｅｓｗa ｐ",
    "panｃakｅswa ｐ",
    "pancａｋesｗａp",
    "pancakｅswap",
    "pancａkeswap",
    "pancakesｗa ｐ",
    "pａnｃakeｓｗa ｐ",
    "pａncａkeswa ｐ",
    "pａncａkｅswａ ｐ",
    "pａnｃａkｅswａp",
    "pａncａｋeｓwａ ｐ",
    "panｃａkｅｓwａp",
    "panｃａｋeswａp",
    "pancaｋeswａp",
    "pａncakeｓｗａp",
    "pａncaｋｅsｗａ ｐ",
    "pａncakeｓｗa ｐ",
    "pancaｋeｓｗa ｐ",
    "pａnｃaｋeｓwap",
    "pａnｃakｅｓwａp",
    "pancａｋeｓwａp",
    "pａncakｅswa ｐ",
    "panｃaｋeｓwａ ｐ",
    "pａncａkｅsｗａ ｐ",
    "pａnｃakesｗａp",
    "pａncakｅｓｗａ ｐ",
    "pancａｋesｗa ｐ",
    "pａnｃakeｓwa ｐ",
    "panｃaｋeｓwａp",
    "pａncakeswa ｐ",
    "pancaｋｅswａ ｐ",
    "panｃakeｓｗap",
    "pａnｃaｋｅｓｗａ ｐ",
    "pancａｋeｓｗａ ｐ",
    "pａncａｋeｓｗａp",
    "pancaｋｅsｗap",
    "panｃａｋeswa ｐ",
    "pancａkｅｓwa ｐ",
    "panｃakesｗａp",
    "pａnｃakeｓwａp",
    "pancaｋeｓｗａ ｐ",
    "panｃaｋｅswap",
    "panｃａｋｅｓｗａ ｐ",
    "panｃａｋｅsｗａp",
    "pancaｋｅsｗa ｐ",
    "panｃaｋesｗa ｐ",
    "panｃａkesｗap",
    "pａnｃakesｗａ ｐ",
    "pａncａｋeｓｗａ ｐ",
    "panｃaｋｅｓwa ｐ",
    "pａncaｋeｓwａp",
    "pａnｃａkｅsｗap",
    "panｃａｋeｓwap",
    "pancａｋｅswa ｐ",
    "panｃaｋeswa ｐ",
    "pａncａkｅｓｗａ ｐ",
    "panｃaｋeｓwap",
    "pａnｃａｋeswａp",
    "panｃakｅｓwａ ｐ",
    "pancakeｓｗa ｐ",
    "pａncaｋｅsｗa ｐ",
    "pａnｃakeswａp",
    "pａnｃａｋeｓｗa ｐ",
    "pａncａｋeｓwa ｐ",
    "pａncａkｅｓｗap",
    "pａncaｋｅｓwａ ｐ",
    "pancaｋesｗａ ｐ",
    "panｃaｋｅsｗap",
    "pancakｅｓｗap",
    "pａncａｋｅswａ ｐ",
    "pａncａｋｅswa ｐ",
    "pａnｃａkeｓｗａ ｐ",
    "pancａkｅｓｗａ ｐ",
    "pａncaｋｅｓwａp",
    "pancakｅｓｗa ｐ",
    "pａnｃakeｓwap",
    "pancakｅｓwa ｐ",
    "pａnｃakｅｓｗa ｐ",
    "pａnｃａｋeｓwａ ｐ",
    "pａncａｋeswａ ｐ",
    "pancａkｅswap",
    "pａncａkｅｓwａp",
    "pａncａｋｅｓｗap",
    "pａnｃakｅsｗa ｐ",
    "pａncａkeｓwａ ｐ",
    "panｃakeｓwa ｐ",
    "panｃａｋｅｓwa ｐ",
    "pａnｃａkeswａ ｐ",
    "pａnｃａkｅｓwａp",
    "panｃaｋｅｓwａ ｐ",
    "pancａkeｓwａ ｐ",
    "panｃakeｓwａ ｐ",
    "pancakesｗap",
    "pancａｋｅswap",
    "pａncａｋeｓwａp",
    "panｃａkeswａp",
    "pａncaｋｅｓｗap",
    "pａnｃaｋeswａp",
    "pancａｋeｓwａ ｐ",
    "pａncａkeswａp",
    "panｃａkeｓｗａ ｐ",
    "panｃaｋeswａ ｐ",
    "pancａｋeｓwa ｐ",
    "pａncaｋeswa ｐ",
    "pancaｋｅｓｗａ ｐ",
    "pａnｃａkeｓwap",
    "pａncａｋｅｓwa ｐ",
    "panｃａkｅswa ｐ",
    "panｃａｋｅｓｗa ｐ",
    "pａnｃａkｅｓｗａ ｐ",
    "pａnｃａｋeswap",
    "pａnｃakｅsｗａ ｐ",
    "pancaｋｅswap",
    "panｃakeswa ｐ",
    "panｃａｋｅｓwａp",
    "pａncａｋeｓｗa ｐ",
    "panｃaｋｅｓwａp",
    "pancａｋesｗap",
    "pancａkｅｓwap",
    "pａnｃaｋesｗap",
    "pａncakｅｓwａp",
    "pａncａkeｓｗａp",
    "panｃａｋｅｓｗap",
    "pancaｋｅｓwap",
    "pａnｃａkｅｓｗap",
    "pａncａkｅｓwａ ｐ",
    "pancａkeswａ ｐ",
    "pａnｃakeswap",
    "panｃａkｅsｗａ ｐ",
    "pancakｅｓwap",
    "pancａｋｅswａ ｐ",
    "panｃａkeｓwａp",
    "panｃakｅｓwa ｐ",
    "pａnｃａｋｅｓｗa ｐ",
    "pａnｃａｋｅswａ ｐ",
    "panｃａkｅsｗap",
    "pancａｋeswap",
    "pａncａｋｅｓwap",
    "panｃaｋｅswａ ｐ",
    "panｃａｋｅsｗap",
    "pancａｋｅｓｗａp",
    "pancaｋeｓwａp",
    "pancａkesｗap",
    "pａncａkesｗａp",
    "pａncaｋｅsｗap",
    "pancａｋeswａp",
    "pａnｃaｋｅｓｗａp",
    "pａncａｋｅswａp",
    "panｃａkｅｓｗa ｐ",
    "panｃaｋｅｓwap",
    "pａncaｋｅｓｗa ｐ",
    "panｃａkeswa ｐ",
    "panｃａｋeswap",
    "pancａｋｅｓwａ ｐ",
    "pａncaｋeｓwap",
    "pancakeｓwａ ｐ",
    "pancaｋeswａ ｐ",
    "pａncakesｗa ｐ",
    "pancａkｅｓwａ ｐ",
    "pａncaｋｅswap",
    "pancakｅｓwａp",
    "pancａkeswa ｐ",
    "panｃａｋeｓｗａp",
    "pａncakeｓwａp",
    "panｃakesｗａ ｐ",
    "pａnｃａkｅswａ ｐ",
    "pａncａkeｓwａp",
    "pancakeｓwa ｐ",
    "pａncaｋesｗａp",
    "pａnｃａkeｓwa ｐ",
    "pancａkｅsｗap",
    "pａnｃaｋｅｓwａ ｐ",
    "pａncａｋｅsｗａ ｐ",
    "pancａｋesｗａ ｐ",
    "pａnｃａｋｅsｗａ ｐ",
    "pａnｃａkesｗap",
    "pａncａkｅswap",
    "pancａkeｓｗａp",
    "pancａkｅｓｗａp",
    "panｃakeｓｗａ ｐ",
    "pａncａｋｅｓwａ ｐ",
    "pａnｃａｋｅsｗa ｐ",
    "panｃａkｅswａ ｐ",
    "pancａkｅsｗａ ｐ",
    "panｃakeswap",
    "pancakeｓｗａp",
    "panｃａkeｓwap",
    "pａnｃａkesｗａ ｐ",
    "panｃａkesｗa ｐ",
    "panｃaｋeswａp",
    "pａnｃａkｅｓwap",
    "panｃａkｅｓwa ｐ",
    "pａncaｋeswap",
    "pａncａｋesｗa ｐ",
    "pａncaｋｅswa ｐ",
    "panｃakｅsｗa ｐ",
    "pａncakｅｓｗa ｐ",
    "pａnｃａkeｓｗａp",
    "pａnｃａkｅｓwa ｐ",
    "pａncａｋesｗａ ｐ",
    "pａnｃａkｅｓｗａp",
    "pancaｋeｓwa ｐ",
    "pａnｃaｋeswａ ｐ",
    "pancａkｅsｗa ｐ",
    "pａnｃａｋｅｓwap",
    "pａncａkｅswａp",
    "panｃａkｅｓwａ ｐ",
    "panｃakesｗa ｐ",
    "pａnｃaｋesｗa ｐ",
    "pａncａｋｅｓｗａ ｐ",
    "pａnｃａkｅswap",
    "panｃaｋesｗａ ｐ",
    "panｃａｋｅsｗa ｐ",
    "pancakeswａp",
    "pancaｋeｓｗap",
    "pａncaｋeswａ ｐ",
    "pancａkeｓｗa ｐ",
    "pancａｋeｓwap",
    "panｃakeｓｗａp",
    "panｃakeｓｗa ｐ",
    "pａncaｋesｗａ ｐ",
    "pａncaｋeｓｗａp",
    "pancａkeｓwap",
    "pａncａkeswap",
    "panｃakｅｓｗａ ｐ",
    "pａncａkeｓwap",
    "panｃａkeｓwａ ｐ",
    "pａnｃaｋｅｓwap",
    "pａnｃaｋｅswa ｐ",
    "pａnｃａｋeｓｗａ ｐ",
    "panｃaｋeｓｗa ｐ",
    "pａncａｋeｓwap",
    "panｃａｋｅｓｗａp",
    "panｃａｋｅswap",
    "pａnｃａｋｅｓｗａ ｐ",
    "pａncakesｗap",
    "pａnｃａkｅsｗa ｐ",
    "panｃａｋesｗa ｐ",
    "pancaｋｅsｗａp",
    "pancaｋeｓwap",
    "panｃａkｅsｗa ｐ",
    "pancａｋｅsｗａp",
    "pａncaｋｅswａp",
    "pancaｋｅｓwａp",
    "pancａｋｅswａp",
    "pａncakｅswａ ｐ",
    "panｃａkeｓwa ｐ",
    "pancａｋeswａ ｐ",
    "pａnｃakｅswａ ｐ",
    "pａncａkｅｓｗa ｐ",
    "pａnｃakｅｓｗａp",
    "panｃａｋeｓwａp",
    "pａnｃａkｅsｗａ ｐ",
    "panｃａｋｅswa ｐ",
    "pancaｋesｗａp",
    "pａnｃａｋesｗap",
    "pａncakｅswap",
    "panｃａｋｅsｗａ ｐ",
    "pａncａｋeｓｗap",
    "pａnｃaｋesｗａ ｐ",
    "panｃakｅｓwａp",
    "pancａkｅsｗａp",
    "pａnｃaｋeswa ｐ",
    "panｃaｋesｗap",
    "panｃaｋｅｓｗa ｐ",
    "panｃakｅswap",
    "pancａkｅswａ ｐ",
    "pａnｃａkeｓｗap",
    "pａncａｋesｗａp",
    "pａnｃakｅｓwａ ｐ",
    "panｃａkｅｓwap",
    "pａncakesｗａp",
    "pａnｃaｋeｓwa ｐ",
    "pancａkｅｓｗa ｐ",
    "panｃａkｅｓｗａ ｐ",
    "pancａｋeｓｗap",
    "pａncakｅｓwap",
    "pａnｃakeｓｗａ ｐ",
    "pancakｅsｗap",
    "pａncakeｓwａ ｐ",
    "pａnｃａｋeｓｗａp",
    "panｃakｅｓｗap",
    "panｃａｋeｓwａ ｐ",
    "pancakｅsｗa ｐ",
    "pａncakｅｓｗａp",
    "pａnｃａｋｅｓwa ｐ",
    "panｃakｅｓｗａp",
    "pａncａkｅｓwap",
    "pancａｋeswa ｐ",
    "panｃａｋｅswａ ｐ",
    "pancakesｗａ ｐ",
    "pａnｃakｅswa ｐ",
    "pａnｃａkeswａp",
    "pａnｃａkesｗa ｐ",
    "pａncａｋｅswap",
    "panｃaｋeｓｗａ ｐ",
    "pａnｃaｋｅｓwａp",
    "pａnｃakesｗa ｐ",
    "pａncａｋeswａp",
    "pａnｃaｋesｗａp",
    "pａncａｋｅｓｗａp",
    "pａncaｋeｓwa ｐ",
    "pａncａkesｗap",
    "panｃａkｅswap",
    "pａncakesｗａ ｐ",
    "pａnｃakeswa ｐ",
    "pancａｋｅsｗa ｐ",
    "panｃａkeｓｗa ｐ",
    "pancａｋｅsｗap",
    "pａnｃａｋesｗａp",
    "panｃaｋｅswａp",
    "pａnｃａkｅsｗａp",
    "pａnｃａｋeｓwａp",
    "pancａｋeｓｗａp",
    "pancakｅswａ ｐ",
    "pancakｅswa ｐ",
    "pａnｃａｋｅswa ｐ",
    "pａncakeｓwap",
    "pａnｃａｋｅsｗａp",
    "pａncａkesｗa ｐ",
];
const newList = [];

for (let i in listToClear) {
    const key = listToClear[i];
    if (!listToExclude.includes(key)) {
        newList.push(key);
    }
}

console.log(newList.length, listToClear.length);
// console.log(newList);
fs.writeFileSync("./filterArray.json", JSON.stringify(newList), "utf-8");
